// species.ts — appat-du-nord-v13
// 21 Quebec freshwater species, alphabetical (English name)
// FR/EN bilingual, full encyclopedia data per spec

export type ActivityLevel = 'HOT' | 'ACTIVE' | 'SLOW' | 'CLOSED'

export interface SubType {
  name: string
  nameFr: string
  description: string
  descriptionFr: string
  imageFile: string
}

export interface TournamentRef {
  name: string
  date: string
  location: string
  notes?: string
}

export interface Species {
  id: string
  // Names
  nameEn: string
  nameFr: string
  name: string // display (FR default)
  scientificName: string
  // Description
  tagline: string
  taglineFr: string
  appearance: string
  appearanceFr: string
  habitat: string
  habitatFr: string
  seasonalBehavior: string
  seasonalBehaviorFr: string
  // Images
  imageFile?: string
  image?: string
  subtypes?: SubType[]
  // Sizes
  avgSize: string
  maxSize: string
  legalSize?: string
  legalSizeFr?: string
  possessionNote?: string
  possessionNoteFr?: string
  // Records
  quebecRecord?: string
  quebecRecordFr?: string
  quebecRecordOfficial?: boolean
  // Conditions
  waterTemp: string
  bestMonths: string // EN
  bestMonthsFr: string
  quebecSeason: string
  monthlyActivity: ActivityLevel[]
  // Gear
  bestLures: string[]
  lureImages: string[]
  gear?: string[]
  techniques?: string[]
  techniquesFr?: string[]
  // Meta
  proTips: string[]
  proTipsFr?: string[]
  catchRelease?: boolean
  bestLakes?: string[]
  tournaments?: TournamentRef[]
}

export const speciesData: Species[] = [
  // 1. Atlantic Salmon
  {
    id: 'atlantic-salmon',
    nameEn: 'Atlantic Salmon',
    nameFr: 'Saumon atlantique / Ouananiche',
    name: 'Saumon atlantique',
    scientificName: 'Salmo salar',
    image: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Atlantic_salmon_fish.jpg',
    tagline: 'The silver king of Quebec rivers.',
    taglineFr: 'Le roi argenté des rivières du Québec.',
    appearance: 'Silver body with black spots, sea-run form is bright chrome. Landlocked ouananiche has more pronounced spots, slightly smaller.',
    appearanceFr: 'Corps argenté avec taches noires. L\'ouananiche (landlocked) est légèrement plus petite avec des taches plus marquées.',
    habitat: 'Clear, cold, fast-flowing rivers. Ouananiche: Lac Saint-Jean tributaries, Saguenay system.',
    habitatFr: 'Rivières claires, froides, rapides. Ouananiche: tributaires du Lac Saint-Jean, système Saguenay.',
    seasonalBehavior: 'Spring and fall migration runs. Summer holding in cool deep pools. Ouananiche accessible year-round in select waters.',
    seasonalBehaviorFr: 'Migrations printanières et automnales. L\'été, tient dans les fosses fraîches et profondes.',
    avgSize: '50–90 cm',
    maxSize: '120 cm+',
    legalSize: 'Varies by river zone — check MRNF regulations',
    legalSizeFr: 'Varie selon la zone de rivière — consulter le MRNF',
    possessionNote: 'Heavily regulated. Many rivers catch-and-release only. Permit required.',
    possessionNoteFr: 'Très réglementé. Beaucoup de rivières en remise à l\'eau obligatoire. Permis requis.',
    quebecRecord: 'Ouananiche: ~5 kg, Lac Saint-Jean system (community reported)',
    quebecRecordFr: 'Ouananiche : ~5 kg, système Lac Saint-Jean (rapporté)',
    quebecRecordOfficial: false,
    waterTemp: '8–14°C optimal',
    bestMonths: 'June, September, October',
    bestMonthsFr: 'Juin, septembre, octobre',
    quebecSeason: 'June – October (river dependent)',
    monthlyActivity: ['CLOSED','CLOSED','CLOSED','CLOSED','SLOW','HOT','ACTIVE','SLOW','HOT','HOT','SLOW','CLOSED'],
    bestLures: ['Grey Ghost','Orange Grey Ghost','Mickey Finn','Black Nose Dace','Muddler Minnow','Woolly Bugger','Royal Wulff','Adams','Elk Hair Caddis','Mepps Aglia','Panther Martin','Rapala Countdown','Little Cleo'],
    lureImages: [],
    gear: ['8–9 ft light/medium spinning rod or 5–7 wt fly rod','Fluorocarbon leaders','Landing net'],
    proTips: [
      'Always check if the river requires a salmon fishing permit before heading out.',
      'Ouananiche in Lac Saint-Jean tributaries are accessible mid-summer — target morning hours.',
      'Fly fishing with a wet fly swung across the current is deadly in classic Quebec salmon pools.',
    ],
    proTipsFr: [
      'Vérifiez toujours si un permis de pêche au saumon est requis avant de partir.',
      'L\'ouananiche dans les tributaires du Lac Saint-Jean est accessible à mi-été — ciblez les matins.',
    ],
    catchRelease: true,
    bestLakes: ['Lac Saint-Jean'],
    tournaments: [],
  },

  // 2. Arctic Char
  {
    id: 'arctic-char',
    nameEn: 'Arctic Char',
    nameFr: 'Omble chevalier',
    name: 'Omble chevalier',
    scientificName: 'Salvelinus alpinus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Salvelinusalpinus.jpg',
    tagline: 'Cold water legend of Quebec\'s northern lakes.',
    taglineFr: 'La légende des eaux froides du nord québécois.',
    appearance: 'Silver to pink flanks with pale spots, reddish belly during spawn. Similar to brook trout but less colourful.',
    appearanceFr: 'Flancs argentés à roses avec taches pâles, ventre rougeâtre en période de fraie. Similaire à l\'omble de fontaine.',
    habitat: 'Deep, cold oligotrophic lakes. Northern and subarctic Quebec. Often found near thermocline in summer.',
    habitatFr: 'Lacs oligotrophes profonds et froids. Nord et subarctique québécois. Souvent près de la thermocline en été.',
    seasonalBehavior: 'Active in cold water year-round. Best in spring/fall when near surface. Summer: deep near thermocline.',
    seasonalBehaviorFr: 'Actif en eau froide toute l\'année. Meilleur au printemps/automne près de la surface. Été: en profondeur.',
    avgSize: '35–55 cm',
    maxSize: '80 cm+',
    legalSize: 'Check specific zone regulations',
    legalSizeFr: 'Consulter le règlement spécifique à la zone',
    possessionNote: 'Remote waters — verify zone-specific regulations',
    possessionNoteFr: 'Eaux éloignées — vérifier le règlement de la zone spécifique',
    quebecRecord: 'Reported specimens from northern Quebec outfitters: 6–8 kg',
    quebecRecordFr: 'Spécimens rapportés par des pourvoiries du nord québécois: 6–8 kg',
    quebecRecordOfficial: false,
    waterTemp: '4–12°C optimal',
    bestMonths: 'June, September, October',
    bestMonthsFr: 'Juin, septembre, octobre',
    quebecSeason: 'Year-round in some northern zones',
    monthlyActivity: ['ACTIVE','ACTIVE','ACTIVE','ACTIVE','HOT','HOT','SLOW','SLOW','HOT','HOT','ACTIVE','ACTIVE'],
    bestLures: ['Williams Wabler','Little Cleo','Tube jigs','Swedish Pimple','Woolly Bugger','Muddler Minnow'],
    lureImages: [],
    gear: ['Medium-light spinning rod or 5–7 wt fly','Cold-water spoon box','Fluorocarbon leaders'],
    proTips: [
      'Arctic char are found primarily in remote northern Quebec outfitter waters.',
      'Small to medium spoons retrieved erratically trigger aggressive strikes.',
      'Cold water slows metabolism — slow down your retrieve.',
    ],
    proTipsFr: [
      'L\'omble chevalier se retrouve principalement dans les pourvoiries du nord québécois.',
      'Les petites à moyennes cuillères récupérées de façon erratique provoquent des attaques agressives.',
    ],
    catchRelease: false,
    bestLakes: ['Lac Mistassini','Lac Waconichi','Lac Pipmuacan'],
    tournaments: [],
  },

  // 3. Brook Trout
  {
    id: 'brook-trout',
    nameEn: 'Brook Trout',
    nameFr: 'Omble de fontaine / Truite mouchetée',
    name: 'Truite mouchetée',
    scientificName: 'Salvelinus fontinalis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Brook_trout_in_water.jpg/800px-Brook_trout_in_water.jpg',
    tagline: 'L\'emblème du Québec. La reine des eaux froides.',
    taglineFr: 'L\'emblème du Québec. La reine des eaux froides.',
    appearance: 'Beautiful char with vermiculated olive back, pale spots, red spots often haloed in blue, and lower fins edged with white/orange-black. Quebec "speckled trout" icon. Also has anadromous/coastal forms on the Côte-Nord.',
    appearanceFr: 'Magnifique omble au dos olive vermiclé, taches pâles, taches rouges cerclées de bleu, nageoires inférieures bordées blanc/orange-noir. Icône québécoise. Formes anadromes/côtières aussi présentes sur la Côte-Nord.',
    habitat: 'Cold, clear, well-oxygenated waters below 15°C. Headwater streams, spring-fed brooks, rivers, ponds, and lakes with gravel/sand bottoms and groundwater influence. Extremely important across Mauricie, Saguenay–Lac-Saint-Jean, Côte-Nord, Gaspésie, Nord-du-Québec.',
    habitatFr: 'Eaux froides, claires, bien oxygénées sous 15°C. Ruisseaux en amont, sources, rivières, étangs et lacs à fond graveleux/sableux avec influence d\'eau souterraine. Très important en Mauricie, Saguenay–Lac-Saint-Jean, Côte-Nord, Gaspésie, Nord-du-Québec.',
    seasonalBehavior: 'Spawns fall (late August in north to November), 5–10°C, in gravel redds of streams, lake inlets/outlets, and groundwater upwellings. Eggs incubate through winter. In summer retreats to cold springs, feeder streams, and shaded reaches. Activity peaks on cool mornings/evenings, overcast days, and whenever cold inflow concentrates food.',
    seasonalBehaviorFr: 'Fraie en automne (fin août dans le nord à novembre), 5–10°C, dans des nids de gravier en ruisseaux, entrées/sorties de lacs, et remontées d\'eau souterraine. Œufs incubés tout l\'hiver. En été se réfugie vers les sources froides, ruisseaux affluents et zones ombragées. Activité maximale les matins/soirs frais, jours couverts, près des arrivées d\'eau froide.',
    avgSize: '20–40 cm',
    maxSize: '65 cm+ (rare in remote lakes)',
    legalSize: '20 cm minimum in most zones. Verify zone.',
    legalSizeFr: '20 cm minimum dans la plupart des zones. Vérifiez votre zone.',
    possessionNote: 'Daily limit varies by zone — many brook trout zones have strict limits to protect the fishery.',
    possessionNoteFr: 'La limite quotidienne varie selon la zone — de nombreuses zones ont des limites strictes pour protéger la ressource.',
    quebecRecord: 'Reported: 4+ kg, Lac Mistassini region (community reported)',
    quebecRecordFr: 'Rapporté : 4+ kg, région du Lac Mistassini (communautaire)',
    quebecRecordOfficial: false,
    waterTemp: '8–14°C optimal',
    bestMonths: 'May, June, September, October',
    bestMonthsFr: 'Mai, juin, septembre, octobre',
    quebecSeason: 'April – September (general rule, verify zone)',
    monthlyActivity: ['SLOW','SLOW','SLOW','HOT','HOT','ACTIVE','SLOW','SLOW','HOT','HOT','ACTIVE','SLOW'],
    bestLures: [
      'Muddler Minnow','Woolly Bugger','Royal Coachman','Royal Wulff','Grey Ghost','Orange Grey Ghost',
      'Mickey Finn','Black Nose Dace','La Bostonnais','Paul & Paul','André A.','Pinard','Ventre Rouge du Nord',
      'Galarneau','Neptune','Elk Hair Caddis','Adams / Parachute Adams','Stimulator','Frenchie nymph',
      'Pheasant Tail','Walt\'s Worm','Sexy Walt\'s','San Juan Worm','Mepps Aglia #0–#2','Panther Martin',
      'Blue Fox Vibrax (small)','Little Cleo','Krocodile spoon','Rapala Original Floater','Rapala Countdown',
    ],
    lureImages: [],
    gear: ['5\'6–6\'6 ultralight/light rod','4–8 lb line','4–6 wt fly setup'],
    proTips: [
      'The brook trout is Quebec\'s iconic species — always check zone regulations carefully.',
      'Early morning in beaver ponds with a Woolly Bugger is a classic Quebec experience.',
      'Traditional Quebec streamer patterns like La Bostonnais and Galarneau are deadly on native brookies.',
      'In summer heat, find the cold spring seeps and headwaters.',
    ],
    proTipsFr: [
      'L\'omble de fontaine est l\'espèce emblématique du Québec — vérifiez toujours les règlements de zone.',
      'En matinée dans les étangs de castors avec un Woolly Bugger est une expérience québécoise classique.',
      'Les mouches traditionnelles québécoises comme La Bostonnais et Galarneau sont redoutables.',
    ],
    catchRelease: false,
    bestLakes: ['Lac Mistassini','Lac Edouard','Lac Waconichi','Lac Pipmuacan','Gouin Reservoir','Cabonga Reservoir'],
    tournaments: [],
  },

  // 4. Brown Trout
  {
    id: 'brown-trout',
    nameEn: 'Brown Trout',
    nameFr: 'Truite brune',
    name: 'Truite brune',
    scientificName: 'Salmo trutta',
    image: 'https://upload.wikimedia.org/wikipedia/commons/2/2e/Salmo_trutta.jpg',
    tagline: 'The wary European immigrant. Quebec\'s most challenging trout.',
    taglineFr: 'L\'immigrant européen méfiant. La truite la plus difficile du Québec.',
    appearance: 'Golden-brown with black and red spots (with halos). Adipose fin orange-tipped. Tail less forked than rainbow.',
    appearanceFr: 'Brun-doré avec taches noires et rouges (cerclées). Nageoire adipeuse à bout orange. Queue moins fourchue que l\'arc-en-ciel.',
    habitat: 'Warmer trout water than brook trout. Clear streams, rivers, some stocked lakes. Prefers cover: undercut banks, logs, deep pools.',
    habitatFr: 'Tolérant des eaux plus chaudes que l\'omble de fontaine. Ruisseaux clairs, rivières, certains lacs ensemencés. Préfère les couverts.',
    seasonalBehavior: 'Active spring and fall. Wary in summer, feeds at dawn/dusk. Fall spawning run in rivers.',
    seasonalBehaviorFr: 'Actif au printemps et en automne. Méfiant en été, s\'alimente à l\'aube/crépuscule. Fraie en automne en rivière.',
    avgSize: '35–55 cm',
    maxSize: '80 cm+ (large stocked/wild specimens)',
    legalSize: 'Varies by zone — verify MRNF',
    legalSizeFr: 'Varie selon la zone — vérifier le MRNF',
    possessionNote: 'Check zone-specific limits. Brown trout zones are often supplemented by stocking.',
    possessionNoteFr: 'Vérifiez les limites spécifiques à la zone.',
    quebecRecord: 'Community reported: 6–8 kg from stocked Quebec rivers',
    quebecRecordFr: 'Communautaire : 6–8 kg depuis des rivières ensemencées du Québec',
    quebecRecordOfficial: false,
    waterTemp: '10–18°C optimal',
    bestMonths: 'May, June, September, October',
    bestMonthsFr: 'Mai, juin, septembre, octobre',
    quebecSeason: 'April – October (zone dependent)',
    monthlyActivity: ['SLOW','SLOW','SLOW','HOT','HOT','ACTIVE','SLOW','SLOW','HOT','HOT','ACTIVE','SLOW'],
    bestLures: ['Mepps Aglia','Panther Martin','Rapala Countdown','Rapala Original Floater','Woolly Bugger','Pheasant Tail','Prince Nymph','Hare\'s Ear'],
    lureImages: [],
    gear: ['Light spinning rod','4–6 wt fly rod','4–8 lb line'],
    proTips: [
      'Brown trout are the most wary — approach quietly, use long leaders.',
      'Fish during low-light conditions: dawn, dusk, overcast days.',
      'Match the hatch with dry flies for spectacular surface takes.',
    ],
    proTipsFr: [
      'La truite brune est la plus méfiante — approchez-vous silencieusement, utilisez de longs bas de ligne.',
      'Pêchez aux heures de faible luminosité : aube, crépuscule, journées nuageuses.',
    ],
    catchRelease: false,
    bestLakes: ['Lac Brome','Lac Brompton','Lac Massawippi','Lac Memphremagog'],
    tournaments: [],
  },

  // 5. Burbot
  {
    id: 'burbot',
    nameEn: 'Burbot',
    nameFr: 'Lotte',
    name: 'Lotte',
    scientificName: 'Lota lota',
    image: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Lota_lota_252741459.jpg',
    tagline: 'The nocturnal bottom dweller. Quebec\'s overlooked delicacy.',
    taglineFr: 'Le rôdeur nocturne du fond. La délicatesse méconnue du Québec.',
    appearance: 'Eel-like freshwater cod. Mottled brown-olive. Single chin barbel. Flattened head. Highly distinct.',
    appearanceFr: 'Morue d\'eau douce, allure d\'anguille. Brun-olive marbré. Un barbillon sous le menton. Tête aplatie.',
    habitat: 'Cold, deep lakes and rivers. Often found near rocky or sandy bottom structure in 15–50 m depth.',
    habitatFr: 'Lacs et rivières froids et profonds. Souvent près des fonds rocheux ou sablonneux à 15–50 m.',
    seasonalBehavior: 'Most active in winter — one of the few species that feeds aggressively in cold/ice conditions. Spawns under ice.',
    seasonalBehaviorFr: 'Plus actif en hiver — une des rares espèces à s\'alimenter agressivement sous la glace. Fraie sous la glace.',
    avgSize: '40–60 cm',
    maxSize: '90 cm+',
    legalSize: 'No minimum size in most Quebec zones',
    legalSizeFr: 'Pas de taille minimale dans la plupart des zones du Québec',
    possessionNote: 'Delicious fish — excellent table fare. Check daily limits.',
    possessionNoteFr: 'Excellent poisson de table. Vérifiez les limites quotidiennes.',
    quebecRecord: 'Community: 5–7 kg from deep Quebec lakes',
    quebecRecordFr: 'Communautaire : 5–7 kg des lacs profonds du Québec',
    quebecRecordOfficial: false,
    waterTemp: '2–10°C optimal (peak in near-freezing water)',
    bestMonths: 'January, February, March, December',
    bestMonthsFr: 'Janvier, février, mars, décembre',
    quebecSeason: 'Year-round, peak in winter',
    monthlyActivity: ['HOT','HOT','HOT','SLOW','SLOW','SLOW','SLOW','SLOW','SLOW','SLOW','SLOW','HOT'],
    bestLures: ['Jigging Rap','Blade baits','Bucktail jigs','Gulp Minnow','Paddle-tail swimbaits'],
    lureImages: [],
    gear: ['Medium spinning jig setup','Bottom-contact jigs','Fluorocarbon leaders'],
    proTips: [
      'Burbot are most active at night in winter — set up near bottom and wait.',
      'A glow-tipped jig with a real minnow trailer is devastating under the ice.',
      'Found in the same cold-water lakes as lake trout and whitefish.',
    ],
    proTipsFr: [
      'La lotte est plus active la nuit en hiver — installez-vous près du fond et attendez.',
      'Un jig à pointe luminescente avec un petit vairon est redoutable sous la glace.',
    ],
    catchRelease: false,
    bestLakes: ['Lac Mistassini','Lac Saint-Jean','Gouin Reservoir','Réservoir Manicouagan'],
    tournaments: [],
  },

  // 6. Carp
  {
    id: 'carp',
    nameEn: 'Carp',
    nameFr: 'Carpe',
    name: 'Carpe',
    scientificName: 'Cyprinus carpio',
    image: 'https://upload.wikimedia.org/wikipedia/commons/9/9b/Cyprinus_carpio.jpeg',
    tagline: 'The freshwater giant. Quebec\'s growing carp fishery.',
    taglineFr: 'Le géant d\'eau douce. La pêche à la carpe en pleine expansion au Québec.',
    appearance: 'Large, golden-bronze scaled fish. Two small barbels at mouth. Can exceed 15 kg in Quebec waters.',
    appearanceFr: 'Grand poisson aux écailles brun-doré. Deux petits barbillons à la bouche. Peut dépasser 15 kg dans les eaux québécoises.',
    habitat: 'Warm, productive lakes and rivers. Bottom feeder. St. Lawrence, Ottawa River, major southern Quebec waters.',
    habitatFr: 'Lacs et rivières chauds et productifs. Se nourrit au fond. Saint-Laurent, rivière des Outaouais, grandes eaux du Québec méridional.',
    seasonalBehavior: 'Active from late spring through fall. Feeds heavily in spring when water warms. Summer carp can be sight-fished in shallows.',
    seasonalBehaviorFr: 'Actif du printemps tardif à l\'automne. S\'alimente intensément au printemps. L\'été, peut être pêché à vue dans les hauts-fonds.',
    avgSize: '50–80 cm',
    maxSize: '100 cm+, 20 kg+',
    legalSize: 'No minimum size in most Quebec zones',
    legalSizeFr: 'Pas de taille minimale dans la plupart des zones du Québec',
    possessionNote: 'No daily limit in most zones. Check local regulations.',
    possessionNoteFr: 'Pas de limite quotidienne dans la plupart des zones. Vérifiez le règlement local.',
    quebecRecord: 'Community: 15–17 kg from St. Lawrence River system',
    quebecRecordFr: 'Communautaire : 15–17 kg du fleuve Saint-Laurent',
    quebecRecordOfficial: false,
    waterTemp: '18–24°C optimal',
    bestMonths: 'May, June, July, August',
    bestMonthsFr: 'Mai, juin, juillet, août',
    quebecSeason: 'May – October',
    monthlyActivity: ['CLOSED','CLOSED','SLOW','SLOW','HOT','HOT','HOT','HOT','ACTIVE','SLOW','SLOW','CLOSED'],
    bestLures: ['Corn-style carp rigs (only where legal)','Pack bait / carp terminal kit','Hair rigs','Weights / swivels'],
    lureImages: [],
    gear: ['Heavy feeder / carp rods','Baitrunner reels','Net and mat'],
    proTips: [
      'Only use corn where it is explicitly legal — check local regulations.',
      'Sight-fishing in clear shallows with minimal disturbance is the most exciting carp technique.',
      'Carp are powerful fighters — use a rod with a fighting butt and a reliable drag.',
    ],
    proTipsFr: [
      'N\'utilisez du maïs que là où c\'est explicitement légal — vérifiez le règlement local.',
      'La pêche à vue dans les hauts-fonds clairs est la technique la plus excitante.',
    ],
    catchRelease: false,
    bestLakes: ['Lac Saint-Louis','Lac Saint-François','Lac des Deux Montagnes','Lac Saint-Pierre'],
    tournaments: [],
  },

  // 7. Catfish
  {
    id: 'catfish',
    nameEn: 'Catfish',
    nameFr: 'Barbue de rivière',
    name: 'Barbue de rivière',
    scientificName: 'Ictalurus punctatus (Channel Catfish)',
    image: 'https://upload.wikimedia.org/wikipedia/commons/5/5f/Channel_Catfish.jpg',
    tagline: 'The whiskered fighter of Quebec rivers.',
    taglineFr: 'Le combattant à moustaches des rivières du Québec.',
    appearance: 'Smooth skin (no scales), 8 barbels, forked tail (channel catfish). Can reach large sizes in Quebec rivers.',
    appearanceFr: 'Peau lisse sans écailles, 8 barbillons, queue fourchue (barbue de rivière). Peut atteindre de grandes tailles dans les rivières québécoises.',
    habitat: 'Large rivers and reservoirs. Deep holes, current seams, below dams. St. Lawrence corridor.',
    habitatFr: 'Grandes rivières et réservoirs. Fosses profondes, coutures de courant, en aval des barrages. Corridor du Saint-Laurent.',
    seasonalBehavior: 'Active spring through fall. Feeds primarily at dusk and night. Spawning in warm-water months.',
    seasonalBehaviorFr: 'Actif du printemps à l\'automne. S\'alimente principalement au crépuscule et la nuit. Fraie pendant les mois chauds.',
    avgSize: '40–70 cm',
    maxSize: '100 cm+',
    legalSize: 'No minimum size in most Quebec zones',
    legalSizeFr: 'Pas de taille minimale dans la plupart des zones',
    possessionNote: 'Check daily possession limits for your zone.',
    possessionNoteFr: 'Vérifiez les limites quotidiennes de possession pour votre zone.',
    quebecRecord: 'Community: 12–15 kg from St. Lawrence (reported)',
    quebecRecordFr: 'Communautaire : 12–15 kg du Saint-Laurent (rapporté)',
    quebecRecordOfficial: false,
    waterTemp: '18–25°C optimal',
    bestMonths: 'June, July, August',
    bestMonthsFr: 'Juin, juillet, août',
    quebecSeason: 'May – October',
    monthlyActivity: ['CLOSED','CLOSED','SLOW','SLOW','ACTIVE','HOT','HOT','HOT','ACTIVE','SLOW','SLOW','CLOSED'],
    bestLures: ['Paddle-tail swimbaits','Blade baits','Jig heads','Bottom rigs'],
    lureImages: [],
    gear: ['Medium-heavy rods','Abrasion-resistant line','Circle hooks where appropriate'],
    proTips: [
      'Catfish feed heavily on scent — natural baits like cut fish or nightcrawlers are very effective.',
      'Fish near bottom in deep holes below dams and bridge pillars.',
      'Night fishing produces the biggest catfish.',
    ],
    proTipsFr: [
      'La barbue se nourrit surtout à l\'odorat — les appâts naturels comme les vers sont très efficaces.',
      'Pêchez près du fond dans les fosses profondes en aval des barrages et des piliers de pont.',
    ],
    catchRelease: false,
    bestLakes: ['Lac Saint-Louis','Lac Saint-Pierre','Lac des Deux Montagnes'],
    tournaments: [],
  },

  // 8. Cisco
  {
    id: 'cisco',
    nameEn: 'Cisco',
    nameFr: 'Cisco / Corégone',
    name: 'Cisco',
    scientificName: 'Coregonus artedi',
    image: 'https://upload.wikimedia.org/wikipedia/commons/8/84/Cisco.jpg',
    tagline: 'The schooling silvery forage fish. Excellent ice fishing.',
    taglineFr: 'Le poisson fourrage argenté en bancs. Excellent en pêche sur glace.',
    appearance: 'Slender, silver fish resembling a small herring. Terminal or subterminal mouth. Important prey species.',
    appearanceFr: 'Poisson mince et argenté ressemblant à un petit hareng. Espèce proie importante.',
    habitat: 'Open-water and mid-depth lakes. Often in large schools. Coldwater lakes throughout Quebec.',
    habitatFr: 'Lacs en eau libre à mi-profondeur. Souvent en grands bancs. Lacs d\'eau froide à travers le Québec.',
    seasonalBehavior: 'Near-surface in fall, deeper in summer. Important winter ice fishing target.',
    seasonalBehaviorFr: 'Près de la surface en automne, plus profond en été. Cible importante de pêche sur glace en hiver.',
    avgSize: '20–35 cm',
    maxSize: '45 cm',
    legalSize: 'No minimum size in most zones',
    legalSizeFr: 'Pas de taille minimale dans la plupart des zones',
    possessionNote: 'Often used as live/cut bait for pike, walleye, lake trout.',
    possessionNoteFr: 'Souvent utilisé comme appât vivant pour le brochet, le doré et le touladi.',
    quebecRecord: 'Not tracked officially',
    quebecRecordFr: 'Non suivi officiellement',
    quebecRecordOfficial: false,
    waterTemp: '4–12°C optimal',
    bestMonths: 'January, February, October, November',
    bestMonthsFr: 'Janvier, février, octobre, novembre',
    quebecSeason: 'Year-round (peak winter and fall)',
    monthlyActivity: ['HOT','HOT','SLOW','SLOW','SLOW','SLOW','SLOW','SLOW','SLOW','HOT','HOT','HOT'],
    bestLures: ['Small spoons','Small minnow plugs'],
    lureImages: [],
    gear: ['Light spinning setup'],
    proTips: [
      'Schools of cisco can be located with sonar — they show up as massive clouds mid-water.',
      'Light jigs tipped with maggots or small minnows are classic cisco tactics under the ice.',
      'Cisco make excellent pike and walleye bait.',
    ],
    proTipsFr: [
      'Les bancs de cisco peuvent être localisés au sonar — ils apparaissent comme de grands nuages en mi-eau.',
    ],
    catchRelease: false,
    bestLakes: ['Lac Saint-Jean','Gouin Reservoir','Lac Mistassini'],
    tournaments: [],
  },

  // 9. Lake Sturgeon
  {
    id: 'lake-sturgeon',
    nameEn: 'Lake Sturgeon',
    nameFr: 'Esturgeon jaune',
    name: 'Esturgeon jaune',
    scientificName: 'Acipenser fulvescens',
    image: 'https://upload.wikimedia.org/wikipedia/commons/c/c6/Acipenser_fulvescens_GLERL.jpg',
    tagline: 'The living dinosaur of Quebec waters. Conservation first.',
    taglineFr: 'Le dinosaure vivant des eaux québécoises. La conservation d\'abord.',
    appearance: 'Ancient-looking: bony scutes instead of scales, sucker mouth, 4 barbels, grey-olive body. Can exceed 2m and 100 kg.',
    appearanceFr: 'Allure préhistorique : écussons osseux au lieu d\'écailles, bouche en ventouse, 4 barbillons, corps gris-olive. Peut dépasser 2 m et 100 kg.',
    habitat: 'Large rivers (St. Lawrence, Ottawa) and deep lakes. Bottom dweller on sandy/gravel substrate.',
    habitatFr: 'Grandes rivières (Saint-Laurent, Outaouais) et lacs profonds. Vis au fond sur des substrats sableux/graveleux.',
    seasonalBehavior: 'Slow-moving bottom feeder year-round. Spawning in spring. Lives 100+ years.',
    seasonalBehaviorFr: 'Prédateur de fond lent toute l\'année. Fraie au printemps. Vie de 100+ ans.',
    avgSize: '100–180 cm',
    maxSize: '300 cm+, 100 kg+',
    legalSize: 'CATCH AND RELEASE ONLY in most Quebec waters. Verify before fishing.',
    legalSizeFr: 'REMISE À L\'EAU OBLIGATOIRE dans la plupart des eaux québécoises. Vérifiez avant de pêcher.',
    possessionNote: 'Critically protected in Quebec. Mandatory catch-and-release. Minimum fines apply. Never remove from water.',
    possessionNoteFr: 'Espèce fortement protégée au Québec. Remise à l\'eau obligatoire. Amendes minimales applicables. Ne jamais sortir de l\'eau.',
    quebecRecord: 'Community/historical: individuals exceeding 130 kg in St. Lawrence (reported)',
    quebecRecordFr: 'Communautaire / historique : individus dépassant 130 kg dans le Saint-Laurent (rapporté)',
    quebecRecordOfficial: false,
    waterTemp: '10–20°C',
    bestMonths: 'May, June, September',
    bestMonthsFr: 'Mai, juin, septembre',
    quebecSeason: 'Year-round (catch-and-release only where legal)',
    monthlyActivity: ['SLOW','SLOW','SLOW','SLOW','ACTIVE','ACTIVE','ACTIVE','ACTIVE','ACTIVE','SLOW','SLOW','SLOW'],
    bestLures: ['Bottom rigs with natural bait (where legal)','Heavy gear only where permitted'],
    lureImages: [],
    gear: ['Heavy rod','Strong braid','Landing and release gear — do NOT remove from water'],
    proTips: [
      '⚠️ Lake sturgeon are strictly protected in Quebec — mandatory catch-and-release.',
      'Never remove a sturgeon from the water — even briefly. Keep horizontal, support the body.',
      'If targeting intentionally, verify your specific zone allows it — most do not.',
    ],
    proTipsFr: [
      '⚠️ L\'esturgeon jaune est strictement protégé au Québec — remise à l\'eau obligatoire.',
      'Ne jamais sortir un esturgeon de l\'eau — même brièvement. Gardez-le horizontal dans l\'eau.',
    ],
    catchRelease: true,
    bestLakes: ['Lac Saint-Pierre','Lac des Deux Montagnes','Lac Saint-Louis'],
    tournaments: [],
  },

  // 10. Lake Trout
  {
    id: 'lake-trout',
    nameEn: 'Lake Trout',
    nameFr: 'Touladi / Truite de lac',
    name: 'Touladi',
    scientificName: 'Salvelinus namaycush',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3d/Lake_trout_fishes_salvelinus_namaycush.jpg/800px-Lake_trout_fishes_salvelinus_namaycush.jpg',
    tagline: 'Le géant des profondeurs. Le record officiel du Québec.',
    taglineFr: 'Le géant des profondeurs. Le record officiel du Québec.',
    appearance: 'Long-bodied char with many light spots on darker background; some populations appear silvery; orange/red fins especially in northern fish. Can hybridize with brook trout to form splake. Deeply forked tail is distinctive.',
    appearanceFr: 'Omble à corps allongé avec de nombreuses taches claires sur fond plus foncé; certaines populations semblent argentées; nageoires orange/rouge surtout chez les poissons nordiques. Peut s\'hybrider avec l\'omble de fontaine pour former le splake. Queue profondément fourchue distinctive.',
    habitat: 'Deep, cold oligotrophic lakes with high oxygen; shifts to ~10°C water once lakes stratify. Typical summer depths 18–53 m. Hallmark species of deep Canadian Shield/boreal lakes across Quebec. Predictable use of same spawning grounds makes them productive but vulnerable to pressure.',
    habitatFr: 'Lacs oligotrophes profonds et froids, bien oxygénés; se déplace vers ~10°C une fois la stratification établie. Profondeurs estivales typiques 18–53 m. Espèce emblématique des lacs profonds du Bouclier canadien/boréal du Québec. L\'utilisation prévisible des mêmes frayères les rend productifs mais vulnérables à la pression.',
    seasonalBehavior: 'Predictable seasonal depth shifts: shallow after breakup, deeper with warming water, then back toward spawning shoals in fall (August–November, 1–12 m, on rubble/boulder reefs). Adults feed on cisco, smelt, alewife, sculpins. Spring shallow feeding excellent right after ice-out. Strong philopatry/homing to spawning grounds.',
    seasonalBehaviorFr: 'Déplacements saisonniers prévisibles en profondeur : peu profond après la débâcle, plus profond avec le réchauffement, puis retour vers les frayères en automne (août–novembre, 1–12 m, récifs de cailloux/rochers). Adultes se nourrissent de cisco, éperlan, alose, chabot. Excellente pêche printanière peu après la débâcle. Fort retour aux frayères (philopatrie).',
    avgSize: '50–90 cm',
    maxSize: '130 cm+',
    legalSize: 'Varies by zone — check MRNF regulation for your zone',
    legalSizeFr: 'Varie selon la zone — vérifier le règlement du MRNF pour votre zone',
    possessionNote: 'Daily bag limit typically 2–5 fish depending on zone. Verify before fishing.',
    possessionNoteFr: 'Limite quotidienne généralement 2–5 poissons selon la zone. Vérifiez avant de pêcher.',
    quebecRecord: '🏆 OFFICIAL — 36 kg, Lac Mistassini (confirmed Quebec record)',
    quebecRecordFr: '🏆 OFFICIEL — 36 kg, Lac Mistassini (record du Québec confirmé)',
    quebecRecordOfficial: true,
    waterTemp: '8–12°C optimal',
    bestMonths: 'May, June, September, October',
    bestMonthsFr: 'Mai, juin, septembre, octobre',
    quebecSeason: 'May – September (general, varies by zone)',
    monthlyActivity: ['SLOW','SLOW','SLOW','SLOW','HOT','HOT','ACTIVE','SLOW','HOT','HOT','ACTIVE','SLOW'],
    bestLures: [
      'Williams Wabler / Wobbler','Little Cleo','Sutton Spoon','Len Thompson Canoe spoon','Lucky Strike spoons',
      'Eppinger Huskie Devle / Dardevle','Kastmaster','Pixee spoon','Mooselook Wobbler','White tube jigs',
      'Pearl/glow tube jigs','Bucktail jigs','Heavy paddletail swimbaits','Swedish Pimple',
      'Hopkins / Krocodile jigging spoons','FlatFish','Large Rapala-style minnows','Mepps (large trout sizes)',
    ],
    lureImages: [],
    gear: ['7\' medium/medium-heavy rod','Line-counter or 3000–4000 reel','10–20 lb line','Sonar / downrigger options'],
    proTips: [
      'The official Quebec lake trout record (36 kg, Lac Mistassini) shows what these fish can reach.',
      'In summer, a downrigger or lead-core line is essential to reach fish at 40–80 m.',
      'Spring and fall: spoons over rocky shoals at 5–15 m are deadly.',
      'Always use a leader — lake trout have sharp gill plates that can cut light line.',
    ],
    proTipsFr: [
      'Le record officiel du Québec (36 kg, Lac Mistassini) démontre le potentiel de cette espèce.',
      'En été, un downrigger ou une ligne plomb est essentiel pour atteindre les poissons à 40–80 m.',
    ],
    catchRelease: false,
    bestLakes: ['Lac Mistassini','Lac Albanel','Lac Waconichi','Réservoir Manicouagan','Lac Pipmuacan','Gouin Reservoir','Cabonga Reservoir'],
    tournaments: [],
  },

  // 11. Largemouth Bass
  {
    id: 'largemouth-bass',
    nameEn: 'Largemouth Bass',
    nameFr: 'Achigan à grande bouche',
    name: 'Achigan à grande bouche',
    scientificName: 'Micropterus salmoides',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2b/Largemouth_Bass_%28Micropterus_salmoides%29_June_2023_%28cropped%29.jpg/800px-Largemouth_Bass_%28Micropterus_salmoides%29_June_2023_%28cropped%29.jpg',
    tagline: 'Le combattant des herbiers. Topwater king.',
    taglineFr: 'Le combattant des herbiers. Le roi du topwater.',
    appearance: 'Green to brown-green fish with a dark lateral band; larger mouth than smallmouth, with upper jaw extending beyond the eye; dorsal lobes nearly separated. Built for weed and cover-oriented ambush in warm water. Primarily southern Quebec in the St. Lawrence basin up to Saint-Nicolas, also the Richelieu, Outaouais, and some Estrie lakes.',
    appearanceFr: 'Poisson vert à brun-vert avec bande latérale foncée; grande bouche avec mâchoire supérieure dépassant l\'œil; lobes dorsaux presque séparés. Conçu pour l\'embuscade dans les herbiers en eau chaude. Principalement dans le sud du Québec, bassin du Saint-Laurent jusqu\'à Saint-Nicolas, Richelieu, Outaouais et certains lacs de l\'Estrie.',
    habitat: 'Calm warm waters (~26–29°C) in lakes, reservoirs, ponds, quiet river sections, backwaters, and vegetation-rich habitats. More tolerant of heat and softer bottoms than smallmouth. Weed edges, lily pads, docks, stumps, fallen timber.',
    habitatFr: 'Eaux calmes et chaudes (~26–29°C) : lacs, réservoirs, étangs, sections calmes de rivières, eaux mortes, habitats riches en végétation. Plus tolérant à la chaleur et aux fonds meubles que la petite bouche. Bordures d\'herbiers, nénuphars, quais, souches, bois mort.',
    seasonalBehavior: 'Spawns late spring into summer on soft substrate near emergent vegetation (0.6–1 m nest, 3–5 days hatching). Male guards eggs and fry. Often feeds morning and evening near vegetation and at surface; suspends or uses mid-depth cover during day. Eats fish, insects, crustaceans, worms, amphibians, small mammals. Remains in warm vegetated shallows longer than most sport fish.',
    seasonalBehaviorFr: 'Fraie fin du printemps jusqu\'en été sur substrat meuble près de la végétation émergente (nid 0,6–1 m, éclosion 3–5 jours). Le mâle garde les œufs et les alevins. S\'alimente souvent matin et soir près de la végétation et en surface; suspendu ou dans les couverts en mi-profondeur le jour. Se nourrit de poissons, insectes, crustacés, vers, amphibiens, petits mammifères.',
    avgSize: '30–50 cm',
    maxSize: '65 cm+ (southern Quebec)',
    legalSize: '30 cm minimum in most Quebec zones',
    legalSizeFr: '30 cm minimum dans la plupart des zones du Québec',
    possessionNote: 'Daily limit 5 fish in most zones. Verify your zone. Mandatory C&R during spawning season in some areas.',
    possessionNoteFr: 'Limite quotidienne de 5 poissons dans la plupart des zones. Vérifiez votre zone.',
    quebecRecord: 'Community reported: 4–5 kg from Lac Champlain (Missisquoi Bay)',
    quebecRecordFr: 'Communautaire : 4–5 kg du Lac Champlain (Baie Missisquoi)',
    quebecRecordOfficial: false,
    waterTemp: '18–25°C optimal',
    bestMonths: 'June, July, August, September',
    bestMonthsFr: 'Juin, juillet, août, septembre',
    quebecSeason: 'June – October',
    monthlyActivity: ['CLOSED','CLOSED','CLOSED','SLOW','SLOW','HOT','HOT','HOT','ACTIVE','ACTIVE','SLOW','CLOSED'],
    bestLures: [
      'Johnson Silver Minnow','Weedless spoons with frog/skirt trailer','Senko / stick worm','Plastic worm',
      'Spinnerbait','Chartreuse/white spinnerbait','Buzzbait','Hollow-body frog','Chatterbait',
      'Jigs with trailers','Squarebill crankbait','Swim jig','Texas-rig creature bait',
      'Weightless fluke','Lipless crankbait','Popping frog','Punch rigs','Wacky worms',
    ],
    lureImages: [],
    gear: ['7\'–7\'4 medium-heavy baitcaster','High-speed reel','30–50 lb braid / 12–17 lb fluoro'],
    proTips: [
      'Hollow-body frog over lily pads is one of the most exciting techniques in Quebec fishing.',
      'Early morning topwater action in summer can be spectacular on southern Quebec lakes.',
      'Focus on transitions: weed to open water, wood to sand, light to shadow.',
    ],
    proTipsFr: [
      'La grenouille creuse sur les nénuphars est l\'une des techniques les plus excitantes.',
      'Les attaques topwater matinales en été peuvent être spectaculaires sur les lacs du sud du Québec.',
    ],
    catchRelease: false,
    bestLakes: ['Lac Champlain (Missisquoi Bay)','Lac Brome','Lac Boivin','Lac Aylmer','Lac Saint-Pierre'],
    tournaments: [
      { name: 'Big Bass Challenge Lavaltrie', date: 'June 20', location: 'Lavaltrie, QC', notes: 'Verify dates before travel' },
      { name: 'Big Bass Challenge Lac St-Louis', date: 'July 25', location: 'Lac Saint-Louis, QC', notes: 'Verify dates before travel' },
      { name: 'Big Bass Challenge Cornwall', date: 'October 10', location: 'Cornwall / St. Lawrence', notes: 'Verify dates before travel' },
    ],
  },

  // 12. Muskellunge
  {
    id: 'muskellunge',
    nameEn: 'Muskellunge',
    nameFr: 'Maskinongé',
    name: 'Maskinongé',
    scientificName: 'Esox masquinongy',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Muskellunge.jpg/800px-Muskellunge.jpg',
    tagline: 'Le roi des eaux douces. Le poisson des 10 000 lancers.',
    taglineFr: 'Le roi des eaux douces. Le poisson des 10 000 lancers.',
    appearance: 'Quebec\'s largest freshwater esocid — elongated torpedo body, long duckbill snout, light background with darker bars/spots. Fully scaled cheeks distinguish it from pike. Can exceed 140 cm and 25 kg.',
    appearanceFr: 'Le plus grand esocidé d\'eau douce du Québec — corps en torpille allongé, long museau en bec de canard, fond clair avec barres ou taches foncées. Joues entièrement écaillées. Peut dépasser 140 cm et 25 kg.',
    habitat: 'Clear, warm-ish productive waters: shallow vegetated bays, lake margins, quiet river reaches. Prefers 20–26°C. In hot summer, slides toward deeper/cooler water or stronger current. St. Lawrence basin: rivers Chaudière, Batiscan, Bécancour, Saint-François, Saint-Maurice, Yamaska, Richelieu, L\'Assomption, Outaouais.',
    habitatFr: 'Eaux productives et relativement chaudes : baies végétalisées, marges de lacs, tronçons calmes de rivières. Préfère 20–26°C. En été, se déplace vers les eaux plus fraîches ou les zones de courant. Bassin du Saint-Laurent : rivières Chaudière, Batiscan, Bécancour, Saint-François, Saint-Maurice, Yamaska, Richelieu, L\'Assomption, Outaouais.',
    seasonalBehavior: 'Spawns late April–early June (~12.5°C) in flooded shallow margins. Post-spawn repositions to weed edges and current seams. Summer: deeper breaklines and cooler inflows. Fall trophy window: 12–16°C = peak aggression. Best feeding windows: night, early morning, twilight.',
    seasonalBehaviorFr: 'Fraie fin avril–début juin (~12,5°C) dans les marges peu profondes inondées. Post-fraie : bordures d\'herbiers et coutures de courant. Été : profondeurs et arrivées d\'eau fraîche. Fenêtre trophée automne : 12–16°C = agressivité maximale. Meilleures fenêtres : nuit, tôt le matin, crépuscule.',
    avgSize: '90–120 cm',
    maxSize: '150 cm+, 25 kg+',
    legalSize: '90 cm minimum in most Quebec zones',
    legalSizeFr: '90 cm minimum dans la plupart des zones du Québec',
    possessionNote: 'Strictly regulated. Catch-and-release strongly encouraged. Daily limit 1 fish in most zones.',
    possessionNoteFr: 'Strictement réglementé. Remise à l\'eau fortement encouragée. Limite quotidienne 1 poisson dans la plupart des zones.',
    quebecRecord: 'Community reported: 30 kg+ from St. Lawrence River. Max observed: 142 cm, Lac des Deux Montagnes',
    quebecRecordFr: 'Communautaire : 30 kg+ fleuve Saint-Laurent. Spécimen maximum observé : 142 cm, Lac des Deux Montagnes',
    quebecRecordOfficial: false,
    waterTemp: '15–22°C optimal (falls aggressive at 12–16°C)',
    bestMonths: 'September, October, November',
    bestMonthsFr: 'Septembre, octobre, novembre',
    quebecSeason: 'June 15 – December 1',
    monthlyActivity: ['CLOSED','CLOSED','CLOSED','CLOSED','CLOSED','ACTIVE','ACTIVE','ACTIVE','HOT','HOT','SLOW','CLOSED'],
    bestLures: [
      'Mepps Musky Killer','Mepps Black Fury Musky Killer Tandem','Joe Bucher Buchertail',
      'Double #10 bucktails / Twin Tens','Musky Mayhem Double Cowgirl','Musky Frenzy Stagger Blade',
      'Mad Chasse bucktails','Suick Thriller','Reef Hawg','Hellhound','Phantom Softail',
      'Musky Innovations Bull Dawg','Swimming Dawg','Suzy Sucker','Savage Gear 3D Burbot Ribbon Tail',
      'Joe Bucher Dancin\' Raider','TopRaider','Cisco Kid Topper','Whopper Plopper musky sizes',
      'Judd Musky Inline Buzzbait','Joe Bucher SlopMaster','Rapala Super Shad Rap',
      'Joe Bucher Depth Raider','Believer','Grandma 10-inch','Jake 8–10 inch',
      'Supernatural Headlock / Mattlock','B&N Deep Shad','B&N Shallow Shad','Rapala X-Rap Magnum',
    ],
    lureImages: [],
    gear: ['8\'–9\' heavy/XH muskie rod','Lexa/Komodo-class reel','80–100 lb braid','100 lb+ leaders','Giant net','Pliers','Hook cutters'],
    proTips: [
      'Always execute a figure-8 at the boat — 30% of strikes happen here.',
      'Fall trophy window: 12–16°C = maximum aggression.',
      'Large lures, slow retrieve in cold water.',
      'Steel or titanium leader is mandatory — muskie will cut fluorocarbon clean.',
      'Match lure size to forage: big water = big lures.',
    ],
    proTipsFr: [
      'Faites toujours le figure-8 au bord du bateau — 30% des attaques se produisent ici.',
      'Fenêtre trophée automne 12–16°C = agressivité maximale.',
      'Leader acier ou titane obligatoire — le maskinongé coupe le fluorocarbone net.',
    ],
    catchRelease: false,
    bestLakes: ['Lac des Deux Montagnes','Lac Saint-Louis','Lac Saint-François','Lac Saint-Pierre'],
    tournaments: [
      { name: 'Muskies Canada chapter events', date: 'Varies', location: 'Various Quebec waters', notes: 'Check Muskies Canada for current schedules' },
    ],
  },

  // 13. Northern Pike
  {
    id: 'northern-pike',
    nameEn: 'Northern Pike',
    nameFr: 'Grand brochet',
    name: 'Grand brochet',
    scientificName: 'Esox lucius',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Esox_lucius_ZOO_1.jpg/800px-Esox_lucius_ZOO_1.jpg',
    tagline: 'Le prédateur qui attend. Patient, fulgurant.',
    taglineFr: 'Le prédateur qui attend. Patient, fulgurant.',
    appearance: 'Long, laterally compressed body; broad flattened snout; dorsal and anal fins set far back near the tail. Olive to dark green back with rows of pale bean-shaped spots on sides; cream-white underside. Distinguished from muskie by pale spots on darker body.',
    appearanceFr: 'Corps long, latéralement comprimé; museau aplati large; nageoires dorsale et anale reculées vers la queue. Dos vert olive à vert foncé avec rangées de taches pâles en haricot; ventre crème-blanc. Se distingue du maskinongé par les taches pâles sur un corps plus foncé.',
    habitat: 'Slow, heavily vegetated rivers, marshes, backwaters, and weedy bays. Strong affinity for flooded grass, emergent vegetation, reeds, and soft-current nursery areas. Found across virtually all Quebec rivers and lakes, including the St. Lawrence system and Rivière des Prairies.',
    habitatFr: 'Rivières lentes, très végétalisées, marais, eaux mortes, baies à herbiers. Forte affinité pour les herbes inondées, la végétation émergente, les roseaux et les zones de nurserie à faible courant. Présent dans presque tous les lacs et rivières du Québec, incluant le Saint-Laurent et la Rivière des Prairies.',
    seasonalBehavior: 'Spawns immediately after ice-out (late April–early June, 4–7°C) in flooded wetlands and vegetated margins. Post-spawn shifts back to weed edges. Dawn and dusk are strongest feeding windows in summer. Active spring and fall; in summer seeks deeper/cooler weed lines. Tolerant of low oxygen.',
    seasonalBehaviorFr: 'Fraie juste après la débâcle (fin avril–début juin, 4–7°C) dans les zones humides inondées et les marges végétalisées. Post-fraie : retour sur les bordures d\'herbiers. Fenêtres d\'alimentation : aube et crépuscule. Actif au printemps et en automne; l\'été cherche les herbiers plus profonds et frais. Tolérant au faible oxygène.',
    avgSize: '60–90 cm',
    maxSize: '120 cm+',
    legalSize: '60 cm minimum in most Quebec zones. Lake Saint-Pierre: slot 56–70 cm, limit 1.',
    legalSizeFr: '60 cm minimum dans la plupart des zones du Québec. Lac Saint-Pierre : encadrement 56–70 cm, limite 1.',
    possessionNote: 'Daily limit varies by zone — typically 4–6 fish. Lac Saint-Pierre: 1 fish only.',
    possessionNoteFr: 'Limite quotidienne varie selon la zone — généralement 4–6 poissons. Lac Saint-Pierre : 1 seul poisson.',
    quebecRecord: 'Community reported: 113 cm, Réservoir Gouin',
    quebecRecordFr: 'Communautaire : 113 cm, Réservoir Gouin',
    quebecRecordOfficial: false,
    waterTemp: '10–18°C optimal',
    bestMonths: 'April, May, September, October',
    bestMonthsFr: 'Avril, mai, septembre, octobre',
    quebecSeason: 'April – November',
    monthlyActivity: ['SLOW','SLOW','SLOW','HOT','HOT','ACTIVE','SLOW','SLOW','ACTIVE','HOT','ACTIVE','SLOW'],
    bestLures: [
      'Eppinger Dardevle','Dardevle Weedless','Five of Diamonds spoon','Gibbs Kit-A-Mat',
      'Johnson Silver Minnow','Mepps Giant Killer','Blue Fox Vibrax','Booyah Pikee spinnerbait',
      'Large safety-pin spinnerbaits','Rapala Husky Jerk 14','Bomber Magnum Long A',
      'Reef Runner 900 series','Yo-Zuri Crystal Minnow','Savage Gear 3D Burbot',
      'Large paddle-tail swimbaits','Lunker City Shaker','Berkley PowerBait Ripple Shad',
      'Kalin\'s Lunker Grub','Bucktail jigs','Esox Cobra-style heavy jigs',
      'Bucktail spinners','Topwater prop baits / buzzbaits',
    ],
    lureImages: [],
    gear: ['7\'–8\' MH/H rod','30–65 lb braid','18–30 lb wire or heavy fluoro leader'],
    proTips: [
      'Weed edges at dawn with a fast-retrieved spinnerbait produce explosive strikes.',
      'In warm summer water, search deeper weed lines and structure — pike seek the cold.',
      'Do the figure-8 like you would for muskie — big pike follow lures all the way to the boat.',
    ],
    proTipsFr: [
      'Bordures de végétation à l\'aube avec une cuillère récupérée rapidement.',
      'En eau chaude d\'été, cherchez les profondeurs et structures — le brochet s\'y réfugie.',
      'Faites le figure-8 comme pour le maskinongé — les brochets suivent aussi les leurres.',
    ],
    catchRelease: false,
    bestLakes: ['Gouin Reservoir','Baskatong Reservoir','Cabonga Reservoir','Dozois Reservoir','Lac Saint-Pierre','Lac des Deux Montagnes'],
    tournaments: [
      { name: 'Brochet à Gué Marina Lachine', date: 'May 9', location: 'Lachine / Lac Saint-Louis', notes: 'Verify dates before travel' },
    ],
  },

  // 14. Perch
  {
    id: 'perch',
    nameEn: 'Yellow Perch',
    nameFr: 'Perchaude',
    name: 'Perchaude',
    scientificName: 'Perca flavescens',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Yellow_Perch_%28Perca_flavescens%29_%28cropped%29.jpg/800px-Yellow_Perch_%28Perca_flavescens%29_%28cropped%29.jpg',
    tagline: 'La reine des frites québécoises. La perchaude chérie.',
    taglineFr: 'La reine des frites québécoises. La perchaude chérie.',
    appearance: 'Yellow-green with 6–8 dark vertical bars. Small, spiny-rayed fish. Highly distinctive and beloved in Quebec.',
    appearanceFr: 'Jaune-vert avec 6–8 barres verticales foncées. Petit poisson avec rayons épineux. Très distinctif et aimé au Québec.',
    habitat: 'Shallow to mid-depth lakes, rivers, bays. School-forming — find one, find many.',
    habitatFr: 'Lacs et rivières à faible à mi-profondeur. Forme des bancs — trouvez-en un, vous en trouverez plusieurs.',
    seasonalBehavior: 'Active year-round including under ice. Best in spring (post-spawn) and fall when schools move shallow.',
    seasonalBehaviorFr: 'Actif toute l\'année, y compris sous la glace. Meilleur au printemps (post-fraie) et en automne quand les bancs remontent.',
    avgSize: '15–25 cm',
    maxSize: '35 cm',
    legalSize: 'Lac Saint-Pierre: MORATORIUM on yellow perch through 2027. Check zone before fishing.',
    legalSizeFr: 'Lac Saint-Pierre : MORATOIRE sur la perchaude jusqu\'en 2027. Vérifiez la zone avant de pêcher.',
    possessionNote: '⚠️ Lac Saint-Pierre perch moratorium in effect through 2027. Other zones: check limits.',
    possessionNoteFr: '⚠️ Moratoire sur la perchaude au Lac Saint-Pierre jusqu\'en 2027. Autres zones : vérifiez les limites.',
    quebecRecord: 'Max observed: ~800g (community), various Quebec lakes',
    quebecRecordFr: 'Maximum observé : ~800g (communautaire), divers lacs du Québec',
    quebecRecordOfficial: false,
    waterTemp: '15–22°C optimal',
    bestMonths: 'May, June, October, November, January, February',
    bestMonthsFr: 'Mai, juin, octobre, novembre, janvier, février',
    quebecSeason: 'Year-round',
    monthlyActivity: ['HOT','HOT','HOT','HOT','HOT','ACTIVE','SLOW','SLOW','ACTIVE','HOT','HOT','HOT'],
    bestLures: ['Small jigs','Marabou jigs','Tiny paddletails','Blade baits','Small spoons','Ice jigs for winter'],
    lureImages: [],
    gear: ['Ultralight/light spinning combo'],
    proTips: [
      '⚠️ Yellow perch moratorium at Lac Saint-Pierre is in effect through 2027 — do not target there.',
      'Live minnows under a bobber remains the classic Quebec perch method.',
      'Ice fishing for perch with small Swedish Pimple jigs is a Quebec winter tradition.',
    ],
    proTipsFr: [
      '⚠️ Moratoire sur la perchaude au Lac Saint-Pierre jusqu\'en 2027 — ne les ciblez pas là.',
      'Vairons vivants sous un bouchon — la méthode classique québécoise pour la perchaude.',
    ],
    catchRelease: false,
    bestLakes: ['Lac Boivin','Lac Champlain (Missisquoi Bay)','Lac Brome','Lac Nantel'],
    tournaments: [
      { name: 'Pêche sur Glace (Ice Fishing Derby)', date: 'January 24', location: 'Various Quebec locations', notes: 'Verify dates and locations before travel' },
    ],
  },

  // 15. Rainbow Trout
  {
    id: 'rainbow-trout',
    nameEn: 'Rainbow Trout',
    nameFr: 'Truite arc-en-ciel',
    name: 'Truite arc-en-ciel',
    scientificName: 'Oncorhynchus mykiss',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Close_up_of_rainbow_trout_fish_underwater_oncorhynchus_mykiss.jpg/800px-Close_up_of_rainbow_trout_fish_underwater_oncorhynchus_mykiss.jpg',
    tagline: 'The acrobat of Quebec trout fishing.',
    taglineFr: 'L\'acrobate de la pêche à la truite au Québec.',
    appearance: 'Silvery with pink-red lateral stripe and black spotting on body and fins. Spectacular leaping fighter.',
    appearanceFr: 'Argenté avec bande latérale rose-rouge et taches noires sur le corps et les nageoires. Combattant spectaculaire qui saute.',
    habitat: 'Clear, oxygenated rivers and lakes. Tolerates slightly warmer water than brook trout. Many stocked populations in Quebec.',
    habitatFr: 'Rivières et lacs clairs et oxygénés. Tolère des eaux légèrement plus chaudes que l\'omble de fontaine. Nombreuses populations ensemencées au Québec.',
    seasonalBehavior: 'Active spring and fall. Most stocked fish are targeted spring through early summer. Wild fish active in cold-water season.',
    seasonalBehaviorFr: 'Actif au printemps et en automne. La plupart des poissons ensemencés sont ciblés du printemps au début de l\'été.',
    avgSize: '25–50 cm',
    maxSize: '80 cm+ (stocked trophy or wild specimens)',
    legalSize: 'Varies by zone — check MRNF stocking information for your area',
    legalSizeFr: 'Varie selon la zone — vérifier l\'information d\'ensemencement du MRNF pour votre secteur',
    possessionNote: 'Most rainbow trout in Quebec are stocked. Daily limits are zone-specific.',
    possessionNoteFr: 'La plupart des truites arc-en-ciel au Québec sont ensemencées. Les limites quotidiennes sont spécifiques à la zone.',
    quebecRecord: 'Community / stocked: 6–8 kg (trophy stocked fish)',
    quebecRecordFr: 'Communautaire / ensemencé : 6–8 kg (poissons trophée ensemencés)',
    quebecRecordOfficial: false,
    waterTemp: '10–18°C optimal',
    bestMonths: 'May, June, September, October',
    bestMonthsFr: 'Mai, juin, septembre, octobre',
    quebecSeason: 'April – October (zone dependent)',
    monthlyActivity: ['SLOW','SLOW','SLOW','HOT','HOT','ACTIVE','SLOW','SLOW','HOT','HOT','ACTIVE','SLOW'],
    bestLures: [
      'Mepps Aglia','Panther Martin','Rooster Tail','Blue Fox Vibrax (small)','Acme Phoebe',
      'Little Cleo','Rapala Countdown','Rapala Husky Jerk','Rapala Original Floater',
      'Woolly Bugger','Rabbit Strip Leech','Parachute Adams','Pheasant Tail',
      'Prince Nymph','Hare\'s Ear','Stimulator','X-Caddis',
      'Small silver/gold spoons','Micro crankbaits','Inline spinners with yellow/red-dot patterns',
    ],
    lureImages: [],
    gear: ['5\'6–7\' light rod','4–8 lb line','4–6 wt fly setup'],
    proTips: [
      'Rainbow trout are the most aerial fighters — keep your rod tip up during the fight.',
      'Match the hatch on stocked ponds: early season often sees hatch-matching fly fishing.',
      'Small spinners fished upstream in rivers trigger instinctive strikes.',
    ],
    proTipsFr: [
      'La truite arc-en-ciel est le combattant le plus aérien — gardez la pointe de votre canne levée.',
      'Faites correspondre votre imitation à l\'éclosion sur les étangs ensemencés.',
    ],
    catchRelease: false,
    bestLakes: ['Lac Brome','Lac Brompton','Lac Massawippi','Lac Memphremagog','Lac Aylmer'],
    tournaments: [],
  },

  // 16. Sauger
  {
    id: 'sauger',
    nameEn: 'Sauger',
    nameFr: 'Doré noir',
    name: 'Doré noir',
    scientificName: 'Sander canadensis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/1/13/Sauger_%28Sander_canadensis%29_%2851747095009%29.jpg',
    tagline: 'The darker, underrated cousin of walleye.',
    taglineFr: 'Le cousin plus foncé et sous-estimé du doré jaune.',
    appearance: 'Darker than walleye, distinctive dark blotches on dorsal fin, smaller and more streamlined. Often confused with walleye.',
    appearanceFr: 'Plus foncé que le doré jaune, taches distinctives sur la nageoire dorsale, plus petit et plus fusiforme. Souvent confondu avec le doré jaune.',
    habitat: 'Large rivers with current. St. Lawrence, Ottawa, Richelieu. Prefers faster water than walleye.',
    habitatFr: 'Grandes rivières avec courant. Saint-Laurent, Outaouais, Richelieu. Préfère les eaux plus rapides que le doré jaune.',
    seasonalBehavior: 'Spring run in rivers. Active year-round in large rivers. Lac Saint-Pierre: opens June 1.',
    seasonalBehaviorFr: 'Migration printanière en rivière. Actif toute l\'année dans les grandes rivières. Lac Saint-Pierre : ouvre le 1er juin.',
    avgSize: '25–40 cm',
    maxSize: '55 cm',
    legalSize: '⚠️ Lac Saint-Pierre: Sauger opens June 1 only. Verify zone limits.',
    legalSizeFr: '⚠️ Lac Saint-Pierre : le doré noir s\'ouvre seulement le 1er juin. Vérifiez les limites de la zone.',
    possessionNote: 'Same family as walleye — check zone-specific walleye/sauger combined limits.',
    possessionNoteFr: 'Même famille que le doré — vérifiez les limites combinées doré jaune/doré noir par zone.',
    quebecRecord: 'Max observed: 2.5–3 kg from St. Lawrence system',
    quebecRecordFr: 'Maximum observé : 2.5–3 kg depuis le système du Saint-Laurent',
    quebecRecordOfficial: false,
    waterTemp: '12–18°C optimal',
    bestMonths: 'May, June, September, October',
    bestMonthsFr: 'Mai, juin, septembre, octobre',
    quebecSeason: 'Year-round in many zones (zone-specific)',
    monthlyActivity: ['ACTIVE','ACTIVE','ACTIVE','ACTIVE','HOT','HOT','ACTIVE','SLOW','ACTIVE','HOT','ACTIVE','ACTIVE'],
    bestLures: ['Jigging Rap','Bucktail jigs','Blade baits','Gulp Minnow','Shad Rap','Flicker Minnow','Spinner harness'],
    lureImages: [],
    gear: ['ML/M spinning jig rod'],
    proTips: [
      '⚠️ Lac Saint-Pierre sauger opens June 1 only — be aware of this regulation.',
      'Target fast-water current seams and rocky points in large rivers.',
      'Sauger often hold deeper than walleye in the same zone — fish vertical jigs near bottom.',
    ],
    proTipsFr: [
      '⚠️ Le doré noir au Lac Saint-Pierre ouvre seulement le 1er juin — tenez compte de cette réglementation.',
    ],
    catchRelease: false,
    bestLakes: ['Lac Saint-Pierre','Lac des Deux Montagnes','Lac Saint-Louis','Lac Saint-François'],
    tournaments: [
      { name: 'Festival du Doré Baie-James', date: 'June 25 – July 4', location: 'Baie-James, QC', notes: 'Walleye & sauger event. Verify dates before travel.' },
    ],
  },

  // 17. Smallmouth Bass
  {
    id: 'smallmouth-bass',
    nameEn: 'Smallmouth Bass',
    nameFr: 'Achigan à petite bouche',
    name: 'Achigan à petite bouche',
    scientificName: 'Micropterus dolomieu',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Smallmouth_Bass_%2849561724026%29.jpg/800px-Smallmouth_Bass_%2849561724026%29.jpg',
    tagline: 'Pound for pound, Quebec\'s hardest fighting fish.',
    taglineFr: 'Livre pour livre, le poisson qui se bat le plus fort au Québec.',
    appearance: 'Bronze to olive-brown body, dark mottling/bars, reddish or orange eyes, slightly forked tail, and mouth where upper jaw reaches only to about the middle of the eye. Dorsal lobes are connected. Mainly in southern Quebec, extending farther north than largemouth, present in St. Lawrence and fluvial lakes, multiple watersheds, eastward toward Montmagny.',
    appearanceFr: 'Corps brun à olive-bronze, marbrures/barres foncées, yeux rougeâtres ou orange, queue légèrement fourchue, bouche dont la mâchoire supérieure atteint environ le milieu de l\'œil. Lobes dorsaux connectés. Principalement dans le sud du Québec, s\'étend plus au nord que la grande bouche, présent dans le Saint-Laurent et ses lacs fluviaux, vers l\'est jusqu\'à Montmagny.',
    habitat: 'Prefers ~20°C. Associated with gravel, sand, rock, points, shoals, island edges, talus, and clearer lakes/rivers. More rock/current oriented than largemouth. Often stations under floating docks or along vegetation bordering drop-offs in Quebec.',
    habitatFr: 'Préfère ~20°C. Associé au gravier, sable, roche, pointes, hauts-fonds, rebords d\'îles, éboulis, lacs/rivières plus clairs. Plus orienté rocher/courant que la grande bouche. Se poste souvent sous les quais flottants ou le long de la végétation bordant les dénivelés au Québec.',
    seasonalBehavior: 'Spawns spring to early summer (~16–18°C). Male builds circular nest 30–180 cm on gravel/sand, guards eggs and fry with strong site fidelity. Eats crayfish, fish, amphibians, insects. Major post-winter activity increase around March through warming spring. In winter, groups near bottom. Fall: shallow feeding frenzy before cold.',
    seasonalBehaviorFr: 'Fraie au printemps–début d\'été (~16–18°C). Le mâle construit un nid circulaire de 30–180 cm sur le gravier/sable, garde les œufs et les alevins avec une forte fidélité au site. Se nourrit de crevettes d\'eau douce, poissons, amphibiens, insectes. Grande augmentation d\'activité post-hivernale vers mars. En hiver, se regroupe près du fond. Automne : frénésie alimentaire avant le froid.',
    avgSize: '25–45 cm',
    maxSize: '60 cm+',
    legalSize: '30 cm minimum in most Quebec zones',
    legalSizeFr: '30 cm minimum dans la plupart des zones du Québec',
    possessionNote: 'Daily limit typically 5 fish in most zones. Mandatory C&R during spawning in some zones.',
    possessionNoteFr: 'Limite quotidienne généralement 5 poissons dans la plupart des zones.',
    quebecRecord: 'Community reported: 3.5–4 kg from Lac Champlain area',
    quebecRecordFr: 'Communautaire : 3.5–4 kg depuis la région du Lac Champlain',
    quebecRecordOfficial: false,
    waterTemp: '18–24°C optimal',
    bestMonths: 'June, July, August, September',
    bestMonthsFr: 'Juin, juillet, août, septembre',
    quebecSeason: 'June – October',
    monthlyActivity: ['CLOSED','CLOSED','CLOSED','SLOW','SLOW','HOT','HOT','HOT','ACTIVE','ACTIVE','SLOW','CLOSED'],
    bestLures: [
      'Walking topwaters','Propbaits','Senko-style worms','4–5 inch soft swimbaits',
      'Ned rig (Z-Man Finesse TRD)','Finesse ShroomZ heads','Tube jigs','Great Lakes Finesse Juvy Craw',
      'Drop-shot worm','Berkley MaxScent Flat Worm','Megabass Vision 110','Hair jigs / marabou jigs',
      'Outkast Feider Fly','Keitech FAT Swing Impact','Savage Gear Ned Craw',
      'Small crankbaits','Leadhead swimbaits','Spybaits (DUO Realis Spinbait 80)',
      'Jigs and finesse craws','Poppers',
    ],
    lureImages: [],
    gear: ['6\'10–7\'2 medium spinning rod','2500 reel','Braid-to-fluoro leader'],
    proTips: [
      'Smallmouth in clear Quebec lakes are the most line-shy fish — go light with 8–10 lb fluoro.',
      'Rocky shoals at dawn with a walking topwater is quintessential Quebec smallmouth fishing.',
      'The Ned rig is devastatingly effective on finicky smallmouth in clear water.',
    ],
    proTipsFr: [
      'L\'achigan à petite bouche dans les lacs clairs du Québec est le plus méfiant — utilisez du fluorocarbone léger.',
      'Les récifs rocheux à l\'aube avec un topwater est la pêche à l\'achigan par excellence au Québec.',
    ],
    catchRelease: false,
    bestLakes: ['Lac Champlain (Missisquoi Bay)','Lac Memphremagog','Lac Massawippi','Lac Tremblant','Lac Nominingue (Grand)'],
    tournaments: [
      { name: 'Big Bass Challenge Lavaltrie', date: 'June 20', location: 'Lavaltrie, QC', notes: 'Verify dates before travel' },
      { name: 'Big Bass Challenge Lac St-Louis', date: 'July 25', location: 'Lac Saint-Louis', notes: 'Verify dates before travel' },
    ],
  },

  // 18. Splake
  {
    id: 'splake',
    nameEn: 'Splake',
    nameFr: 'Togue / Splake',
    name: 'Splake',
    scientificName: 'Salvelinus namaycush × Salvelinus fontinalis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/0/0f/Splake_-_33749894874.jpg',
    tagline: 'The lake trout × brook trout hybrid. Grows fast, fights hard.',
    taglineFr: 'L\'hybride touladi × omble de fontaine. Croît vite, se bat fort.',
    appearance: 'Cross between lake trout and brook trout. More rounded tail than lake trout, more spotting than typical laker. Rare in wild Quebec.',
    appearanceFr: 'Croisement entre touladi et omble de fontaine. Queue plus arrondie que le touladi, plus de taches.',
    habitat: 'Cold, deep lakes similar to lake trout. Often in stocked reservoirs and remote lakes.',
    habitatFr: 'Lacs froids et profonds similaires au touladi. Souvent dans les réservoirs ensemencés et les lacs éloignés.',
    seasonalBehavior: 'Similar to lake trout — deep in summer, near surface in spring/fall.',
    seasonalBehaviorFr: 'Similaire au touladi — profond en été, près de la surface au printemps/automne.',
    avgSize: '35–60 cm',
    maxSize: '80 cm+',
    legalSize: 'Varies by zone — check stocking records for your lake',
    legalSizeFr: 'Varie selon la zone — vérifier les registres d\'ensemencement pour votre lac',
    possessionNote: 'Zone-specific — many splake waters are specially regulated stocking zones.',
    possessionNoteFr: 'Spécifique à la zone — de nombreux plans d\'eau à splake sont des zones d\'ensemencement spécialement réglementées.',
    quebecRecord: 'Not officially tracked (hybrid species)',
    quebecRecordFr: 'Non suivi officiellement (espèce hybride)',
    quebecRecordOfficial: false,
    waterTemp: '6–12°C optimal',
    bestMonths: 'May, June, September, October',
    bestMonthsFr: 'Mai, juin, septembre, octobre',
    quebecSeason: 'Zone-specific (follows lake trout regulations in most cases)',
    monthlyActivity: ['SLOW','SLOW','SLOW','SLOW','HOT','HOT','ACTIVE','SLOW','HOT','HOT','ACTIVE','SLOW'],
    bestLures: ['Williams Wabler','Little Cleo','Mepps Aglia','Tube jigs','Rapala Countdown'],
    lureImages: [],
    gear: ['Medium-light spinning rod'],
    proTips: [
      'Splake grow faster than lake trout — a 3-year-old splake can match a 6-year-old lake trout.',
      'Look for stocked splake in designated provincial fishing access areas.',
      'Use same techniques as lake trout: spoons, jigging, trolling.',
    ],
    proTipsFr: [
      'Les splake croissent plus vite que les touladis — un splake de 3 ans peut égaler un touladi de 6 ans.',
    ],
    catchRelease: false,
    bestLakes: ['Various stocked Quebec lakes — check MRNF ensemencement records'],
    tournaments: [],
  },

  // 19. Tiger Muskie
  {
    id: 'tiger-muskie',
    nameEn: 'Tiger Muskie',
    nameFr: 'Maskinongé tigré',
    name: 'Maskinongé tigré',
    scientificName: 'Esox masquinongy × Esox lucius',
    image: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Tiger_Muskie%2C_Lake_Saint_Clair.jpg',
    tagline: 'L\'hybride féroce. Brochet × maskinongé.',
    taglineFr: 'L\'hybride féroce. Brochet × maskinongé.',
    appearance: 'Distinctive tiger stripes (vertical bars unlike true muskie spots). More aggressive than either parent species. Usually sterile.',
    appearanceFr: 'Rayures tigrées distinctives (barres verticales contrairement aux taches du maskinongé pur). Plus agressif. Généralement stérile.',
    habitat: 'Same waters as parent species. St. Lawrence system, larger lakes and rivers.',
    habitatFr: 'Mêmes eaux que les espèces parentales. Système Saint-Laurent, grands lacs et rivières.',
    seasonalBehavior: 'Similar to muskellunge — most aggressive in fall when water cools. More willing to strike than pure muskie.',
    seasonalBehaviorFr: 'Similaire au maskinongé — plus agressif en automne quand l\'eau refroidit. Plus enclin à mordre que le maskinongé pur.',
    avgSize: '70–100 cm',
    maxSize: '130 cm+',
    legalSize: 'Typically same as muskellunge — 90 cm in most zones. Verify.',
    legalSizeFr: 'Généralement même que le maskinongé — 90 cm dans la plupart des zones. Vérifiez.',
    possessionNote: 'Same regulations as muskellunge in most Quebec zones.',
    possessionNoteFr: 'Mêmes règlements que le maskinongé dans la plupart des zones du Québec.',
    quebecRecord: 'Max observed: community reports from Lac des Deux Montagnes region',
    quebecRecordFr: 'Maximum observé : rapports communautaires de la région du Lac des Deux Montagnes',
    quebecRecordOfficial: false,
    waterTemp: '15–22°C optimal',
    bestMonths: 'September, October, November',
    bestMonthsFr: 'Septembre, octobre, novembre',
    quebecSeason: 'June 15 – December 1 (follows muskellunge season)',
    monthlyActivity: ['CLOSED','CLOSED','CLOSED','CLOSED','CLOSED','ACTIVE','ACTIVE','ACTIVE','HOT','HOT','SLOW','CLOSED'],
    bestLures: [
      'Bucktails (all sizes)','Glider baits','Topwater muskie lures','Trolling cranks',
      'Joe Bucher Buchertail','Mepps Musky Killer','Bull Dawg swimbaits',
    ],
    lureImages: [],
    gear: ['8\'–9\' heavy/XH muskie rod','80–100 lb braid','100 lb+ leaders','Giant net','Pliers','Hook cutters'],
    proTips: [
      'Tiger muskie tend to strike more readily than pure muskellunge — still use the figure-8.',
      'Striped pattern lures that mimic their own pattern can be especially effective.',
      'Same gear as pure muskellunge is required — they grow just as large.',
    ],
    proTipsFr: [
      'Le maskinongé tigré mord plus facilement que le maskinongé pur — faites quand même le figure-8.',
    ],
    catchRelease: false,
    bestLakes: ['Lac des Deux Montagnes','Lac Saint-Louis','Lac Saint-François'],
    tournaments: [],
  },

  // 20. Walleye
  {
    id: 'walleye',
    nameEn: 'Walleye',
    nameFr: 'Doré jaune',
    name: 'Doré jaune',
    scientificName: 'Sander vitreus',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Walleye_%28Sander_vitreus%29_%281%29.jpg/800px-Walleye_%28Sander_vitreus%29_%281%29.jpg',
    tagline: 'Le poisson des Québécois. Champion de la table.',
    taglineFr: 'Le poisson des Québécois. Champion de la table.',
    appearance: 'Elongated percid with olive-gold sides, distinctive white-tipped lower tail lobe, reflective tapetum eyes adapted to dim light, and canine-like teeth. Quebec also documents a blue phenotype in northern waters.',
    appearanceFr: 'Percidé allongé aux flancs olive-dorés, lobe inférieur de la queue blanc distinctif, yeux réfléchissants adaptés à la faible luminosité, et dents canines. Québec documente aussi un phénotype bleu dans les eaux nordiques.',
    habitat: 'Prefers cool water (~13–21°C), large lakes, reservoirs, rivers, turbid or stained systems. Strongly associated with rock, gravel, sand, shoals, moderate current, deep pools, and low-light habitat. Widely distributed from freshwater St. Lawrence northward to James Bay. Strong fisheries in Abitibi-Témiscamingue, Outaouais, Lac Saint-Jean, Mauricie, Nord-du-Québec.',
    habitatFr: 'Préfère les eaux fraîches (~13–21°C), grands lacs, réservoirs, rivières, systèmes turbides ou colorés. Fortement associé aux fonds rocheux, gravier, sable, hauts-fonds, courant modéré et habitat à faible luminosité. Large distribution du Saint-Laurent jusqu\'à la Baie James. Pêcheries importantes en Abitibi-Témiscamingue, Outaouais, Lac Saint-Jean, Mauricie, Nord-du-Québec.',
    seasonalBehavior: 'Spawns early April–late June (~7–9°C) on rock/gravel river runs, rapids, dam tailraces, tributary mouths. Strong annual homing to same spawning sites. Post-spawn feeding is especially aggressive. Peak feeding: dawn, dusk, and night — especially in clear water. In turbid systems, may remain active shallow all day. Dams can block migrations.',
    seasonalBehaviorFr: 'Fraie début avril–fin juin (~7–9°C) sur les tronçons rocheux/graveleux, rapides, queues de barrage, embouchures de tributaires. Fort retour annuel aux mêmes sites de fraie. L\'alimentation post-fraie est particulièrement agressive. Pics d\'alimentation : aube, crépuscule, nuit — surtout en eau claire. Dans les systèmes turbides, peut rester actif dans les eaux peu profondes toute la journée.',
    avgSize: '35–60 cm',
    maxSize: '85 cm+',
    legalSize: 'Lac Saint-Pierre: walleye limit 2 fish. Other zones vary — verify MRNF.',
    legalSizeFr: 'Lac Saint-Pierre : limite doré jaune 2 poissons. Autres zones varient — vérifier le MRNF.',
    possessionNote: 'Typically 5 fish/day in most Quebec zones. Lac Saint-Pierre limit is 2. Always verify your zone.',
    possessionNoteFr: 'Généralement 5 poissons/jour dans la plupart des zones du Québec. Limite au Lac Saint-Pierre : 2. Vérifiez toujours votre zone.',
    quebecRecord: 'Community reported: 82 cm, Lac Saint-Pierre',
    quebecRecordFr: 'Communautaire : 82 cm, Lac Saint-Pierre',
    quebecRecordOfficial: false,
    waterTemp: '12–18°C optimal',
    bestMonths: 'May, June, September, October, January, February',
    bestMonthsFr: 'Mai, juin, septembre, octobre, janvier, février',
    quebecSeason: 'May – March (ice fishing included)',
    monthlyActivity: ['HOT','HOT','HOT','ACTIVE','HOT','ACTIVE','SLOW','SLOW','ACTIVE','HOT','ACTIVE','ACTIVE'],
    bestLures: [
      'Rapala Jigging Rap','VMC Bucktail Jig','VMC Hot Skirt Glow Jig','Judd Walleye Jig',
      'Marabou jigs','Berkley PowerBait Gulp Minnow','Berkley Power Grub','Berkley Power Worm',
      'Berkley Ripple Shad / minnow plastics','Sassy Shad','Rapala CrushCity swimbaits',
      'Round ball jig heads','Football jigs','Northland Thumper Jig','Blade baits',
      'Bio-Minnow Vertical Jig','Guppy blade bait','Rapala Shad Rap','Berkley Flicker Minnow',
      'Berkley Flicker Shad','Rapala Down Deep Husky Jerk','Cotton Cordell Wally Diver',
      'Rapala Tail Dancer','Reef Runner Deep Little Ripper','Storm Hot \'N Tot',
      'Yo-Zuri Crystal Minnow Deep Diver','Spinner harness / crawler harness',
      'Finesse minnows / worm-shaped plastics',
    ],
    lureImages: [],
    gear: ['6\'6–7\'2 ML/M spinning rod','2500–3000 reel','8–12 lb braid + fluoro leader'],
    proTips: [
      'Pêchez aux heures creuses — lumière tamisée (crépuscule, aube) déclenche l\'alimentation.',
      'Jig le long du fond avec vitesse et pauses régulières.',
      'Harnais à chenille pour la traîne lente en eaux profondes.',
      'Points rocheux et courants — cherchez les structures immergées.',
    ],
    proTipsFr: [
      'Pêchez aux heures creuses — lumière tamisée (crépuscule, aube) déclenche l\'alimentation.',
      'Jig le long du fond avec vitesse et pauses régulières.',
    ],
    catchRelease: false,
    bestLakes: ['Lac Saint-Pierre','Lac des Deux Montagnes','Lac Saint-Louis','Gouin Reservoir','Baskatong Reservoir','Grand Lac Victoria'],
    tournaments: [
      { name: 'Festival du Doré Baie-James', date: 'June 25 – July 4', location: 'Baie-James, QC', notes: 'Premier Quebec walleye event. Verify dates before travel.' },
      { name: 'Big Rock Derby', date: 'June 5 – July 13', location: 'Various Quebec waters', notes: 'Verify dates before travel.' },
    ],
  },

  // 21. Whitefish
  {
    id: 'whitefish',
    nameEn: 'Lake Whitefish',
    nameFr: 'Grand corégone',
    name: 'Grand corégone',
    scientificName: 'Coregonus clupeaformis',
    image: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Coregonus_clupeaformis.jpg',
    tagline: 'The overlooked deep-water Quebec delicacy.',
    taglineFr: 'La délicatesse d\'eau profonde méconnue du Québec.',
    appearance: 'Silvery-white, slender, small head, subterminal mouth. Hump-backed profile. Excellent eating — mild, white, flaky flesh.',
    appearanceFr: 'Argenté-blanc, mince, petite tête, bouche subterminale. Profil bossé. Excellente chair — douce, blanche, feuilletée.',
    habitat: 'Deep, cold lakes. Often found in open water or over sandy/rocky bottom at 10–40 m depth. Pan-Quebec distribution.',
    habitatFr: 'Lacs profonds et froids. Souvent en eau libre ou au-dessus d\'un fond sableux/rocheux à 10–40 m. Distribution pan-québécoise.',
    seasonalBehavior: 'Deep in summer. Near surface in fall and spring. Strong ice fishing target in winter.',
    seasonalBehaviorFr: 'Profond en été. Près de la surface en automne et au printemps. Excellente cible de pêche sur glace en hiver.',
    avgSize: '35–55 cm',
    maxSize: '70 cm+',
    legalSize: 'No minimum size in most Quebec zones',
    legalSizeFr: 'Pas de taille minimale dans la plupart des zones du Québec',
    possessionNote: 'Check daily limits for your zone. Great eating fish — highly recommended.',
    possessionNoteFr: 'Vérifiez les limites quotidiennes pour votre zone. Excellent poisson de table — fortement recommandé.',
    quebecRecord: 'Not officially tracked',
    quebecRecordFr: 'Non suivi officiellement',
    quebecRecordOfficial: false,
    waterTemp: '4–12°C optimal',
    bestMonths: 'January, February, October, November',
    bestMonthsFr: 'Janvier, février, octobre, novembre',
    quebecSeason: 'Year-round (peak fall and winter)',
    monthlyActivity: ['HOT','HOT','SLOW','SLOW','ACTIVE','SLOW','SLOW','SLOW','SLOW','HOT','HOT','HOT'],
    bestLures: ['Small spoons','Jigging spoons','Flies / small streamers'],
    lureImages: [],
    gear: ['Light / medium-light spinning rig'],
    proTips: [
      'Whitefish school in deep water — use sonar to locate the schools, then drop a jig straight down.',
      'Maggots or small minnows on a light jig under the ice is the classic whitefish method.',
      'Smoked whitefish is one of Quebec\'s great culinary traditions.',
    ],
    proTipsFr: [
      'Le grand corégone se rassemble en profondeur — utilisez le sonar pour localiser les bancs.',
      'Asticots ou petits vairons sur un léger jig sous la glace est la méthode classique.',
    ],
    catchRelease: false,
    bestLakes: ['Lac Saint-Jean','Gouin Reservoir','Lac Mistassini','Réservoir Manicouagan','Lac Pipmuacan'],
    tournaments: [],
  },
]

// Alphabetical order verification (already sorted by English name):
// 1. Atlantic Salmon, 2. Arctic Char, 3. Brook Trout, 4. Brown Trout, 5. Burbot,
// 6. Carp, 7. Catfish, 8. Cisco, 9. Lake Sturgeon, 10. Lake Trout,
// 11. Largemouth Bass, 12. Muskellunge, 13. Northern Pike, 14. Perch, 15. Rainbow Trout,
// 16. Sauger, 17. Smallmouth Bass, 18. Splake, 19. Tiger Muskie, 20. Walleye, 21. Whitefish
