export type TipSpecies = 'maskinonge' | 'brochet' | 'achigan' | 'dore' | 'truite' | 'esturgeon' | 'omble-chevalier' | 'touladi' | 'perchaude' | 'carpe' | 'barbotte' | 'cisco' | 'lotte' | 'coregone' | 'crapet' | 'tous'

export interface Tip {
  id: string
  species: TipSpecies
  speciesFR: string
  text: string
  textEN: string
  stars: number
}

export const tips: Tip[] = [
  { id: 't1', species: 'maskinonge', speciesFR: 'Maskinongé', text: "Le figure-8 n'est pas un extra: sur les eaux à maskinongé du Québec, plusieurs attaques arrivent au bateau. Termine chaque lancer par un grand huit large, profond et accéléré dans les virages.", textEN: "The figure-eight is not optional: on Quebec musky water, many strikes happen at boatside. Finish every cast with a wide, deep figure-eight and speed up through the turns.", stars: 5 },
  { id: 't2', species: 'maskinonge', speciesFR: 'Maskinongé', text: "Quand l'eau d'automne tombe autour de 12 à 16 °C, entre dans ta vraie fenêtre trophée. C'est souvent le moment de prioriser les grosses structures, les longues bordures et les poissons d'une seule touche.", textEN: "When fall water drops into roughly the 12 to 16°C range, you enter the true trophy window. That's often the time to focus on major structure, long edges, and fish that may give you only one shot.", stars: 5 },
  { id: 't3', species: 'maskinonge', speciesFR: 'Maskinongé', text: "Commence gros, surtout sur les lacs à réputation: bucktails massifs, swimbaits et glide baits de 8 à 12 pouces filtrent souvent les petits poissons et déclenchent les vraies femelles.", textEN: "Start big, especially on well-known musky waters: large bucktails, swimbaits, and 8- to 12-inch glide baits often filter out smaller fish and trigger mature females.", stars: 4 },
  { id: 't4', species: 'maskinonge', speciesFR: 'Maskinongé', text: "Un avançon acier ou titane bien monté est essentiel. Sur un maskinongé, ce n'est pas le moment d'économiser sur le terminal tackle.", textEN: "A properly built steel or titanium leader is essential. With musky, terminal tackle is not the place to cut corners.", stars: 4 },
  { id: 't5', species: 'maskinonge', speciesFR: 'Maskinongé', text: "Pêche le maskinongé comme un jeu de confiance: cadence stable, angles répétés, zéro lancer bâclé. Le poisson des 10 000 lancers récompense surtout la discipline.", textEN: "Fish musky as a confidence game: steady cadence, repeated angles, and no lazy casts. The fish of 10,000 casts rewards discipline more than anything.", stars: 5 },
  { id: 't6', species: 'brochet', speciesFR: 'Brochet', text: "Au lever du jour, longe les bordures d'herbiers avec une cuillère ou un spinnerbait ramené juste assez vite pour rester au-dessus des tiges. Le brochet y embusque souvent son premier repas.", textEN: "At dawn, run weed edges with a spoon or spinnerbait retrieved just fast enough to stay above the stems. Pike often set up there for their first feed of the day.", stars: 3 },
  { id: 't7', species: 'brochet', speciesFR: 'Brochet', text: "En plein été, quitte les baies trop chaudes et cherche le premier accès à l'eau plus fraîche: cassure, trou voisin, bordure externe d'herbier ou embouchure avec courant.", textEN: "In midsummer, leave overheated bays and look for the first access to cooler water: a breakline, nearby hole, outside weed edge, or current-fed mouth.", stars: 3 },
  { id: 't8', species: 'brochet', speciesFR: 'Brochet', text: "Fais aussi un figure-8 pour le brochet. Sur plusieurs lacs du Québec, les gros sujets suivent longtemps avant de décider au dernier instant.", textEN: "Do a figure-eight for pike too. On many Quebec lakes, bigger fish follow a long way before committing at the last second.", stars: 3 },
  { id: 't9', species: 'achigan', speciesFR: 'Achigan', text: "Pour la grande bouche, pense couvert chaud: herbiers, quais, nénuphars, bois noyé et petites baies sombres. Plus l'eau chauffe, plus le couvert devient important.", textEN: "For largemouth, think warm cover: weeds, docks, lily pads, flooded wood, and dark shallow bays. The warmer the water gets, the more important cover becomes.", stars: 2 },
  { id: 't10', species: 'achigan', speciesFR: 'Achigan', text: "Pour la petite bouche, vise roches, plateaux, pointes et veines de courant. Au Québec, elle adore souvent la transition entre roche propre et eau plus profonde.", textEN: "For smallmouth, target rock, flats, points, and current lanes. In Quebec, it often loves the transition between clean rock and nearby deeper water.", stars: 2 },
  { id: 't11', species: 'achigan', speciesFR: 'Achigan', text: "Le drop-shot brille autour des piliers de quai et des tombants nets en milieu d'été. Garde le plomb léger mais assez lourd pour rester exactement dans la zone.", textEN: "The drop-shot shines around dock posts and sharp drop-offs in midsummer. Keep the weight light but heavy enough to stay exactly in the strike zone.", stars: 4 },
  { id: 't12', species: 'achigan', speciesFR: 'Achigan', text: "À l'aube, un popper ou un walking bait discret peut produire vite sur la grande bouche. Laisse toujours une courte pause après l'impact avant de commencer l'animation.", textEN: "At dawn, a subtle popper or walking bait can produce fast on largemouth. Always let the bait sit briefly after splashdown before starting the retrieve.", stars: 3 },
  { id: 't13', species: 'dore', speciesFR: 'Doré', text: "Le doré aime les heures de faible lumière. Au Québec, l'aube, le crépuscule et les journées couvertes prolongent souvent la morsure sur les hauts-fonds et les pointes rocheuses.", textEN: "Walleye love low-light periods. In Quebec, dawn, dusk, and overcast days often extend the bite on shoals and rocky points.", stars: 3 },
  { id: 't14', species: 'dore', speciesFR: 'Doré', text: "Au jig, cherche le fond sans le labourer. Le meilleur rythme est souvent une suite de petits bonds propres suivis d'une courte pause juste au-dessus du substrat.", textEN: "With a jig, find bottom without plowing it. The best cadence is often a series of clean short hops followed by a brief pause just above the substrate.", stars: 3 },
  { id: 't15', species: 'dore', speciesFR: 'Doré', text: "En traîne lente, un harnais à chenille reste une valeur sûre pour couvrir proprement une cassure ou un plateau. Garde une vitesse juste assez lente pour que la présentation travaille sans tourner n'importe comment.", textEN: "On a slow troll, a crawler harness remains a reliable way to cover a breakline or flat cleanly. Keep speed just slow enough for the presentation to work without spinning wildly.", stars: 3 },
  { id: 't16', species: 'dore', speciesFR: 'Doré', text: "Cherche les structures qui combinent roche et courant modéré: pointes, barres, têtes d'îles et aval de rapides. Le doré se place rarement au hasard sur les grandes eaux québécoises.", textEN: "Look for structure combining rock and moderate current: points, bars, island heads, and downstream current seams. Walleye on big Quebec water rarely position at random.", stars: 2 },
  { id: 't17', species: 'truite', speciesFR: 'Truite', text: "Pour la truite en rivière, ajuste la taille et la vitesse de ton leurre à ce qui dérive vraiment. Une petite cuillère ou un petit poisson nageur bien présenté vaut mieux qu'un leurre trop voyant.", textEN: "For trout in rivers, match lure size and speed to what is actually drifting. A small spoon or minnow bait presented cleanly often outperforms something overly loud.", stars: 3 },
  { id: 't18', species: 'truite', speciesFR: 'Truite', text: "En été, le touladi impose la profondeur. Utilise l'électronique pour rester au bon niveau près de la thermocline, souvent bien plus important que de choisir la couleur parfaite.", textEN: "In summer, lake trout demand depth precision. Use electronics to stay on the right level near the thermocline, often more important than picking the perfect color.", stars: 4 },
  { id: 't19', species: 'truite', speciesFR: 'Truite', text: "Dès que l'eau dépasse environ 15 °C, l'omble de fontaine devient vulnérable au stress. Cherche les entrées d'eau froide, les fosses ombragées et les secteurs plus oxygénés.", textEN: "Once water climbs above about 15°C, brook trout become vulnerable to stress. Look for cold inflows, shaded holes, and more highly oxygenated water.", stars: 3 },
  { id: 't20', species: 'maskinonge', speciesFR: 'Maskinongé', text: "Travaille les cassures rapides de 6 à 15 pieds juste à l'extérieur des herbiers clairsemés. Sur des plans d'eau comme le lac Saint-Pierre ou le lac des Deux Montagnes, le maskinongé circule souvent sur la bordure externe plutôt qu'au cœur du couvert.", textEN: "Work sharp breaklines that fall from 6 to 15 feet just outside sparse weeds. On waters like Lac Saint-Pierre or Lake of Two Mountains, muskies often travel the outside edge rather than the middle of the cover.", stars: 5 },
  { id: 't21', species: 'maskinonge', speciesFR: 'Maskinongé', text: "Quand le vent pousse l'eau plus chaude dans une baie, commence par les pointes exposées et les premières entrées avant d'aller tout au fond. Les plus gros poissons interceptent souvent là.", textEN: "When wind pushes warmer water into a bay, start on the exposed points and first entrances before going all the way to the back. Bigger fish often intercept there.", stars: 4 },
  { id: 't22', species: 'maskinonge', speciesFR: 'Maskinongé', text: "Alterne leurres bruyants et présentations plus silencieuses dans la même journée. Un maskinongé qui refuse une grosse lame vibrante peut mordre plus tard sur un swimbait souple plus discret.", textEN: "Alternate loud baits and quieter presentations on the same day. A musky that refuses a loud blade may later eat a subtler soft swimbait.", stars: 4 },
  { id: 't23', species: 'maskinonge', speciesFR: 'Maskinongé', text: "À la fin de chaque lancer, garde assez de vitesse pour entrer dans un grand huit large et profond sans casser l'action du leurre. Beaucoup de suivis se transforment là, pas avant.", textEN: "At the end of every cast, keep enough speed to transition into a wide, deep figure-eight without killing the bait. Many follows convert there, not before.", stars: 5 },
  { id: 't24', species: 'maskinonge', speciesFR: 'Maskinongé', text: "Par eau froide d'automne, ralentis sans rendre le leurre mort. Les pauses longues près d'une roche isolée, d'une pointe ou d'une grosse cassure déclenchent souvent les plus gros poissons de l'année.", textEN: "In cold fall water, slow down without making the bait look dead. Long pauses near isolated rock, points, or major breaks often trigger the biggest fish of the year.", stars: 5 },
  { id: 't25', species: 'brochet', speciesFR: 'Brochet', text: "Cherche les herbiers irréguliers, avec trous, angles et petites pointes. Le brochet préfère souvent ces postes d'embuscade aux longues bordures uniformes.", textEN: "Target irregular weed beds with holes, corners, and little points. Pike often prefer those ambush spots over long uniform edges.", stars: 4 },
  { id: 't26', species: 'brochet', speciesFR: 'Brochet', text: "Quand l'eau est légèrement teintée et que le vent ride la surface, un spinnerbait blanc ou chartreuse couvre vite beaucoup d'eau et reste très visible pour le brochet.", textEN: "When water is slightly stained and wind puts a chop on the surface, a white or chartreuse spinnerbait covers water fast and stays highly visible to pike.", stars: 4 },
  { id: 't27', species: 'brochet', speciesFR: 'Brochet', text: "En début de saison, vise les baies peu profondes qui gagnent quelques degrés en après-midi. Sur le brochet, cette petite différence de température peut tout changer.", textEN: "Early in the season, focus on shallow bays that gain a few degrees in the afternoon. For pike, that small temperature change can make all the difference.", stars: 4 },
  { id: 't28', species: 'brochet', speciesFR: 'Brochet', text: "Utilise un avançon discret mais solide, et garde des pinces longues prêtes avant même la touche. Les gros brochets engament parfois plus profond qu'on l'imagine.", textEN: "Use a discreet but strong leader, and keep long pliers ready before the strike even happens. Big pike sometimes eat deeper than you expect.", stars: 5 },
  { id: 't29', species: 'achigan', speciesFR: 'Achigan', text: "Sur les plateaux rocheux, commence avec une présentation de recherche comme jerkbait ou tube, puis ralentis au besoin avec un ver souple. Tu localises d'abord les poissons actifs avant d'insister.", textEN: "On rocky flats, start with a search bait like a jerkbait or tube, then slow down with a soft worm if needed. Locate active fish first, then settle in.", stars: 4 },
  { id: 't30', species: 'achigan', speciesFR: 'Achigan', text: "L'achigan se place souvent sur le premier couvert près de l'eau plus profonde. Si tu trouves un quai, une souche ou une roche isolée au bord d'une cassure, ne passe pas trop vite.", textEN: "Bass often hold on the first piece of cover nearest deeper water. If you find a dock, stump, or isolated rock on the edge of a break, do not rush past it.", stars: 4 },
  { id: 't31', species: 'achigan', speciesFR: 'Achigan', text: "Au lever et au coucher du soleil, un topwater discret peut produire très vite sur les bordures calmes, les quais et les petites anses. Garde quand même un montage de suivi prêt si l'eau s'ouvre sans que le poisson prenne.", textEN: "At dawn and dusk, a subtle topwater can produce fast along calm edges, docks, and small coves. Still keep a follow-up rig ready if a fish boils without eating.", stars: 4 },
  { id: 't32', species: 'achigan', speciesFR: 'Achigan', text: "Après un front froid, raccourcis tes lancers et insiste davantage sur les cibles précises. L'achigan collé au couvert répond souvent après deux ou trois présentations identiques bien placées.", textEN: "After a cold front, shorten your casts and work precise targets harder. Bass pinned to cover often respond after two or three identical, well-placed presentations.", stars: 5 },
  { id: 't33', species: 'dore', speciesFR: 'Doré', text: "Le doré se tient souvent juste à côté du courant principal, pas dedans. En dérive, présente ton jig sur la veine plus lente voisine du gros débit.", textEN: "Walleye often hold just beside the main current, not right in it. On a drift, present your jig in the softer lane next to the strongest flow.", stars: 5 },
  { id: 't34', species: 'dore', speciesFR: 'Doré', text: "Les journées couvertes ou légèrement venteuses gardent souvent le doré plus haut sur les hauts-fonds et les barres rocheuses. C'est souvent le moment de rester moins profond plus longtemps.", textEN: "Cloudy or lightly windy days often keep walleye higher on shoals and rocky bars. That is often when staying shallower for longer pays off.", stars: 4 },
  { id: 't35', species: 'dore', speciesFR: 'Doré', text: "Au jig, cherche le contact avec le fond sans accrocher à chaque mètre. De petits bonds nets et contrôlés prennent généralement plus de dorés qu'une animation trop violente.", textEN: "With a jig, look for bottom contact without snagging every few feet. Small, crisp, controlled hops usually catch more walleye than overly violent motion.", stars: 5 },
  { id: 't36', species: 'dore', speciesFR: 'Doré', text: "En soirée, surveille les pointes balayées par le vent qui donnent accès à un bassin plus profond. Les bancs de dorés s'y déplacent souvent pour monter se nourrir.", textEN: "In the evening, watch windblown points that lead into deeper basins. Walleye schools often move through them as they slide up to feed.", stars: 4 },
  { id: 't37', species: 'truite', speciesFR: 'Truite', text: "En lac clair, éloigne-toi un peu de la rive et lance parallèle au tombant plutôt que directement dessus. La truite suit souvent cette ligne de transition.", textEN: "On clear lakes, back off from shore and cast parallel to the drop rather than straight at it. Trout often patrol that transition line.", stars: 4 },
  { id: 't38', species: 'truite', speciesFR: 'Truite', text: "Après une pluie fraîche, vérifie les entrées d'eau et petits affluents. L'oxygène supplémentaire et la nourriture dérivante y attirent souvent rapidement la truite.", textEN: "After a cool rain, check inflows and small tributary mouths. Added oxygen and drifting food often pull trout in quickly.", stars: 4 },
  { id: 't39', species: 'truite', speciesFR: 'Truite', text: "Quand l'eau est très claire et le soleil haut, réduis la taille de tes leurres et affine ta ligne. La discrétion fait souvent plus que la couleur miracle.", textEN: "When water is very clear and the sun is high, downsize your lures and refine your line. Stealth often matters more than a miracle color.", stars: 4 },
  { id: 't40', species: 'truite', speciesFR: 'Truite', text: "Garde les manipulations très brèves et mouille toujours tes mains avant de toucher la truite. En eau plus chaude, la remise à l'eau rapide devient encore plus importante.", textEN: "Keep handling extremely brief and always wet your hands before touching trout. In warmer water, quick release matters even more.", stars: 5 },
  { id: 't41', species: 'esturgeon', speciesFR: 'Esturgeon', text: "Pour l'esturgeon, cible un fond ferme près d'une fosse ou d'un chenal et laisse ton montage bien posé. La première touche peut être discrète avant la vraie traction. Remise à l'eau obligatoire.", textEN: "For sturgeon, target firm bottom near a hole or channel and keep your rig sitting cleanly. The first bite can be subtle before the real pull. Catch and release only.", stars: 5 },
  { id: 't42', species: 'esturgeon', speciesFR: 'Esturgeon', text: "Prépare ton décrocheur, une surface mouillée et ton plan de remise à l'eau avant même de ferrer un gros esturgeon. Évite de le sortir inutilement de l'eau et relâche-le calmement. Remise à l'eau obligatoire.", textEN: "Have your unhooking tools, wet surface, and release plan ready before you even hook a big sturgeon. Avoid taking it out of the water unnecessarily and release it calmly. Catch and release only.", stars: 5 },
  // Omble Chevalier
  { id: 't43', species: 'omble-chevalier', speciesFR: 'Omble Chevalier', text: "L'omble chevalier vit dans les eaux froides et profondes des grands lacs nordiques du Québec. En été, il se concentre près de la thermocline; cherche-le entre 20 et 40 mètres selon la saison.", textEN: "Arctic char inhabits cold, deep waters of Quebec's northern lakes. In summer, they concentrate near the thermocline; look for them between 20 and 40 metres depending on season.", stars: 5 },
  { id: 't44', species: 'omble-chevalier', speciesFR: 'Omble Chevalier', text: "Les petites cuillères brillantes et les leurres de type streamer imitant des épinoches ou des ciscoes produisent bien pour l'omble chevalier. Anime lentement à la profondeur cible.", textEN: "Small bright spoons and streamer-type lures imitating sticklebacks or ciscoes work well for Arctic char. Retrieve slowly at the target depth.", stars: 4 },
  { id: 't45', species: 'omble-chevalier', speciesFR: 'Omble Chevalier', text: "Printemps et automne sont les meilleures saisons pour l'omble chevalier au Québec, quand la thermocline est moins prononcée et que le poisson monte vers des eaux plus accessibles.", textEN: "Spring and fall are the best seasons for Arctic char in Quebec, when the thermocline is less pronounced and fish rise to more accessible depths.", stars: 4 },
  // Touladi
  { id: 't46', species: 'touladi', speciesFR: 'Touladi', text: "En été, le touladi se positionne strictement sous la thermocline dans les eaux froides. Utilise ton échosondeur pour localiser exactement la couche thermique et pêche juste en dessous.", textEN: "In summer, lake trout position strictly below the thermocline in cold water. Use your fishfinder to pinpoint the thermal layer and fish just below it.", stars: 5 },
  { id: 't47', species: 'touladi', speciesFR: 'Touladi', text: "La traîne profonde avec des leurres imitant le cisco ou le corégone est la technique reine pour le touladi en été. Varie la vitesse jusqu'à trouver la cadence qui déclenche les touches.", textEN: "Deep trolling with lures imitating cisco or whitefish is the premier technique for lake trout in summer. Vary your speed until you find the cadence that triggers bites.", stars: 5 },
  { id: 't48', species: 'touladi', speciesFR: 'Touladi', text: "Printemps et automne, le touladi monte en eaux moins profondes. Sur les pointes et les hauts-fonds rocheux, on peut le prendre au lancer avec des cuillères, spinnerbaits ou swimbaits.", textEN: "In spring and fall, lake trout move shallower. On rocky points and shoals, you can catch them casting with spoons, spinnerbaits, or swimbaits.", stars: 4 },
  // Perchaude
  { id: 't49', species: 'perchaude', speciesFR: 'Perchaude', text: "La perchaude se pêche bien en bancs, souvent ancrés sur des hauts-fonds rocheux ou herbeux entre 3 et 8 mètres. Une fois un banc localisé, insiste: il peut y en avoir des centaines.", textEN: "Yellow perch school heavily, often anchored on rocky or weedy flats between 3 and 8 metres. Once you find a school, stay on it — there can be hundreds.", stars: 4 },
  { id: 't50', species: 'perchaude', speciesFR: 'Perchaude', text: "Le jig léger avec queue torsadée chartreuse ou orange produit très bien pour la perchaude. Ajoute un demi-ver de terre sur l'hameçon pour déclencher les plus méfiantes.", textEN: "A light jig with chartreuse or orange twister tail produces very well for perch. Add a half night crawler on the hook to trigger the most reluctant fish.", stars: 3 },
  { id: 't51', species: 'perchaude', speciesFR: 'Perchaude', text: "La pêche sur glace est particulièrement productive pour la perchaude au Québec. Par temps froid et clair, elle se nourrit activement en milieu de journée dans les eaux peu profondes.", textEN: "Ice fishing is particularly productive for yellow perch in Quebec. In cold, clear weather, they feed actively midday in shallow water.", stars: 4 },
  // Carpe
  { id: 't52', species: 'carpe', speciesFR: 'Carpe', text: "La carpe au Québec s'attrape surtout en été avec des montages de fond utilisant du maïs, des boulettes à la pâte d'arachide ou du pain. La rive calme d'une baie peu profonde avec limon est idéale.", textEN: "Carp in Quebec are mainly caught in summer using bottom rigs with corn, peanut paste boilies, or bread. A calm shoreline of a shallow silty bay is ideal.", stars: 3 },
  { id: 't53', species: 'carpe', speciesFR: 'Carpe', text: "Cherche les carpes en surface: quand elles lèvent la tête ou sautent, elles cartographient leur territoire. Lance en amont de ces activités et laisse ton appât tomber lentement.", textEN: "Look for carp at the surface: when they head or jump, they are mapping their territory. Cast upstream of that activity and let your bait sink slowly.", stars: 3 },
  // Barbotte
  { id: 't54', species: 'barbotte', speciesFR: 'Barbotte', text: "La barbotte brune aime les fonds boueux, les herbes denses et les eaux peu oxygénées que d'autres espèces évitent. Pêche en soirée ou la nuit pour les meilleures chances.", textEN: "Brown bullhead favors muddy bottoms, dense weeds, and poorly oxygenated water other species avoid. Fish in the evening or at night for best results.", stars: 3 },
  { id: 't55', species: 'barbotte', speciesFR: 'Barbotte', text: "Un montage de fond simple avec ver de terre ou foie de poulet sur le fond boueux est la méthode classique pour la barbotte. Elle mange par l'odorat, pas par la vue.", textEN: "A simple bottom rig with night crawler or chicken liver on a muddy bottom is the classic method for bullhead. It hunts by smell, not sight.", stars: 3 },
  // Cisco
  { id: 't56', species: 'cisco', speciesFR: 'Cisco', text: "Le cisco vit dans les eaux froides et profondes en été, mais remonte en surface au coucher du soleil pour se nourrir d'insectes. On peut le prendre à la mouche sèche ou au petit leurre de surface ces soirs-là.", textEN: "Cisco lives in cold deep water in summer but rises to the surface at sunset to feed on insects. You can catch them on dry fly or small surface lure on those evenings.", stars: 4 },
  { id: 't57', species: 'cisco', speciesFR: 'Cisco', text: "En hiver, le cisco fraie sous la glace en décembre-janvier. La pêche sur glace près des embouchures de rivières où le cisco se rassemble peut être exceptionnelle cette période.", textEN: "In winter, cisco spawn under the ice in December-January. Ice fishing near river mouths where cisco congregate can be exceptional at this time.", stars: 4 },
  // Lotte
  { id: 't58', species: 'lotte', speciesFR: 'Lotte', text: "La lotte est un poisson nocturne actif toute l'année, même sous la glace. La nuit, elle chasse activement en remontant vers les hauts-fonds; le jour, elle se cache dans les anfractuosités rocheuses.", textEN: "Burbot is a nocturnal fish active year-round, even under ice. At night it hunts actively moving to the shallows; by day it hides in rocky crevices.", stars: 4 },
  { id: 't59', species: 'lotte', speciesFR: 'Lotte', text: "La pêche sur glace nocturne avec un bon poisson mort ou un gros ver est la méthode la plus efficace pour la lotte. Elle est particulièrement active lors des nuits sans lune en janvier-février.", textEN: "Nighttime ice fishing with a dead fish or large worm is the most effective method for burbot. They are particularly active on moonless nights in January-February.", stars: 5 },
  // Corégone
  { id: 't60', species: 'coregone', speciesFR: 'Corégone', text: "Le grand corégone est un poisson de fond en été, tenu par les eaux froides sous la thermocline. La traîne profonde avec de petites cuillères argentées ou des leurres imitant des invertébrés est efficace.", textEN: "Lake whitefish is a bottom fish in summer, held by cold water below the thermocline. Deep trolling with small silver spoons or invertebrate-imitating lures is effective.", stars: 4 },
  { id: 't61', species: 'coregone', speciesFR: 'Corégone', text: "En hiver, le corégone se pêche très bien sur glace avec de petits jigs en tungstène ou des cuillères légères. Il est délicat et méfiant — il faut une ligne fine et des mouvements doux.", textEN: "In winter, whitefish ice fish very well with small tungsten jigs or light spoons. They are subtle and wary — use fine line and gentle movements.", stars: 4 },
  // Crapet
  { id: 't62', species: 'crapet', speciesFR: 'Crapet', text: "Le crapet soleil se pêche facilement avec un simple ver de terre sur hameçon léger, flotteur compris. C'est un excellent poisson pour initier les enfants à la pêche et abondant dans les lacs du Québec.", textEN: "Pumpkinseed sunfish catches easily with a simple earthworm on a light hook with a bobber. It's an excellent fish for introducing children to fishing and abundant in Quebec lakes.", stars: 2 },
  { id: 't63', species: 'crapet', speciesFR: 'Crapet', text: "Le crapet aime les fonds herbeux et peu profonds, surtout autour des quais, des rochers et des racines immergées. Petite mouche sèche ou mouche nymphe l'été: c'est du vrai sport à la canne légère.", textEN: "Pumpkinseed loves weedy shallow bottoms, especially around docks, rocks, and submerged roots. Small dry fly or nymph in summer: it's real sport on light tackle.", stars: 3 },
]
