export interface WaterPermit {
  labelFr: string
  labelEn: string
  url: string
}

export interface Water {
  id: string
  name: string
  nameFr: string
  nameEn: string
  region: string
  imageFile: string
  descFr: string
  descEn: string
  species: string[]
  bestSeason: string
  depth?: string
  size?: string
  boatLaunches: string[]
  weatherRegion: string
  coords: [number, number]
  nearestCity: string
  permits?: WaterPermit[]
}

export const waters: Water[] = [
  // ─── G ───────────────────────────────────────────────────────────────────
  {
    id: 'grand-lac-victoria',
    name: 'Grand Lac Victoria',
    nameFr: 'Grand Lac Victoria',
    nameEn: 'Grand Lake Victoria',
    region: 'Abitibi-Témiscamingue',
    imageFile: 'lake-1.jpg',
    descFr: "Faisant partie du bassin de la rivière des Outaouais, le Grand Lac Victoria est un plan d'eau reculé et peu fréquenté qui récompense les pêcheurs qui font l'effort de s'y rendre. Le doré et le brochet y sont les principales cibles, avec de nombreuses baies peu profondes, des pointes rocheuses et des plateaux productifs. L'été, les herbiers en bordure et les sorties de courant concentrent les prises; l'accès reste limité, ce qui préserve une qualité de pêche au-dessus de la moyenne.",
    descEn: "Part of the Ottawa River system, Grand Lake Victoria is a remote, lightly pressured water that rewards anglers willing to make the effort to reach it. Walleye and northern pike are the primary targets, with numerous shallow bays, rocky points, and productive flats. In summer, weed edges and current exits concentrate fish; access remains limited, which keeps the fishing quality above average.",
    species: ['Doré Jaune', 'Grand Brochet'],
    bestSeason: 'Juin–Août',
    depth: 'Modérée (10–25 m)',
    size: 'Lac moyen (~120 km²)',
    boatLaunches: [
      'Accès via route forestière depuis Val-d\'Or — coordonnées GPS : 47.58, -77.33',
      'Pourvoiries privées avec mise à l\'eau — renseignements locaux requis',
    ],
    weatherRegion: 'Val-d\'Or',
    coords: [47.58, -77.33],
    nearestCity: 'Val-d\'Or',
  },

  // ─── L-A ─────────────────────────────────────────────────────────────────
  {
    id: 'lac-a-leau-claire',
    name: "Lac à l'Eau Claire",
    nameFr: "Lac à l'Eau Claire",
    nameEn: 'Lac à l\'Eau Claire (Clear Water Lake)',
    region: 'Mauricie',
    imageFile: 'lake-2.jpg',
    descFr: "Petit joyau de la Mauricie, ce lac se distingue par une eau exceptionnellement claire et froide qui soutient omble de fontaine, truite arc-en-ciel et touladi. Les cassures nettes, les pointes rocheuses et les zones d'ombrage profond produisent le mieux. La pêche de printemps et d'automne est particulièrement forte; en été, les poissons se réfugient en profondeur pendant les chaleurs. Un incontournable pour les amoureux de la truite au Québec.",
    descEn: "A small gem of the Mauricie, this lake stands out for its exceptionally clear and cold water supporting brook trout, rainbow trout, and lake trout. Sharp breaklines, rocky points, and deep shaded zones produce best. Spring and fall fishing are particularly strong; in summer, fish retreat to depth during heat. An unmissable destination for trout lovers in Quebec.",
    species: ['Truite Mouchetée', 'Truite Arc-en-ciel', 'Touladi'],
    bestSeason: 'Mai–Juin, Septembre–Octobre',
    depth: 'Profond (25–45 m)',
    size: 'Petit lac (< 20 km²)',
    boatLaunches: [
      'Accès depuis Saint-Alexis-des-Monts — Route 349 Nord puis chemin forestier',
      'Rampe rurale — coordonnées GPS : 46.55, -73.08',
    ],
    weatherRegion: 'Trois-Rivières',
    coords: [46.55, -73.08],
    nearestCity: 'Saint-Alexis-des-Monts',
  },
  {
    id: 'lac-albanel',
    name: 'Lac Albanel',
    nameFr: 'Lac Albanel',
    nameEn: 'Lake Albanel',
    region: 'Nord-du-Québec',
    imageFile: 'lake-3.jpg',
    descFr: "Lac reculé du Nord-du-Québec, Albanel offre une pêche dans un cadre sauvage préservé, aux eaux froides et profondes. Touladi, omble de fontaine, doré et grand brochet s'y côtoient. L'accès limité maintient une pression minimale sur les populations de poissons. Accessible principalement par avion ou route de Mistissini, c'est une destination de pourvoirie ou d'expédition. Juin et juillet sont les meilleures périodes avant les canicules.",
    descEn: "A remote lake in Nord-du-Québec, Albanel offers fishing in a pristine wilderness setting with cold, deep waters. Lake trout, brook trout, walleye, and northern pike coexist here. Limited access keeps pressure minimal on fish populations. Accessible mainly by plane or road from Mistissini, it is an outfitter or expedition destination. June and July are the best windows before summer heat sets in.",
    species: ['Touladi', 'Truite Mouchetée', 'Doré Jaune', 'Grand Brochet'],
    bestSeason: 'Juin–Juillet',
    depth: 'Profond (30–60 m)',
    size: 'Grand lac (>200 km²)',
    boatLaunches: [
      'Accès aérien depuis Chibougamau ou Mistissini (hydravion recommandé)',
      'Route d\'accès depuis Mistissini — Route 167 puis routes forestières',
    ],
    weatherRegion: 'Chibougamau',
    coords: [50.88, -73.08],
    nearestCity: 'Mistissini',
  },
  {
    id: 'lac-au-sorcier',
    name: 'Lac au Sorcier',
    nameFr: 'Lac au Sorcier',
    nameEn: 'Lac au Sorcier (Sorcerer Lake)',
    region: 'Mauricie',
    imageFile: 'lake-4.jpg',
    descFr: "Petit lac mauricien réputé pour sa ouananiche (saumon de l'Atlantique enclavé), le lac au Sorcier est un choix de choix pour les amateurs de pêche sportive fine. L'eau fraîche et les structures rocheuses bien marquées en font un lac de début de saison particulièrement fort. Les périodes calmes du matin et du soir, surtout en mai et juin, donnent souvent les meilleures sorties à la mouche ou au leurre.",
    descEn: "A small Mauricie lake known for its landlocked Atlantic salmon (ouananiche), Lac au Sorcier is a top choice for refined sport fishing. The cool water and well-defined rocky structures make it a strong early-season lake. Calm morning and evening periods, especially in May and June, often deliver the best fly or lure sessions.",
    species: ['Ouananiche', 'Truite Mouchetée'],
    bestSeason: 'Mai–Juin',
    depth: 'Modérée (15–30 m)',
    size: 'Petit lac (< 15 km²)',
    boatLaunches: [
      'Accès depuis Saint-Alexis-des-Monts — Route 349, puis chemin local',
      'Mise à l\'eau informelle — coordonnées GPS : 46.60, -73.30',
    ],
    weatherRegion: 'Trois-Rivières',
    coords: [46.60, -73.30],
    nearestCity: 'Saint-Alexis-des-Monts',
  },
  {
    id: 'lac-aylmer',
    name: 'Lac Aylmer',
    nameFr: 'Lac Aylmer',
    nameEn: 'Lake Aylmer',
    region: 'Chaudière-Appalaches',
    imageFile: 'lake-5.jpg',
    descFr: "Lac peu profond et bien réchauffé de Chaudière-Appalaches, le lac Aylmer est excellent pour une pêche estivale variée: doré, brochet, achigan et maskinongé s'y trouvent tous. Les herbiers étendus, les quais et les zones de sable fin font partie des structures clés. De juin à août, les matins calmes et les périodes de vent modéré déclenchent souvent l'activité des prédateurs actifs sur les herbiers et leurs bordures.",
    descEn: "A shallow, well-warmed lake in Chaudière-Appalaches, Lac Aylmer is excellent for varied summer fishing: walleye, pike, bass, and musky are all present. Extensive weeds, docks, and sandy flats are key structures. From June to August, calm mornings and moderate wind periods often trigger predator activity over and around weed edges.",
    species: ['Doré Jaune', 'Grand Brochet', 'Achigan', 'Maskinongé'],
    bestSeason: 'Juin–Août',
    depth: 'Peu profond (5–15 m)',
    size: 'Lac moyen (~40 km²)',
    boatLaunches: [
      'Rampe municipale de Disraeli — Rue du Lac, Disraeli, QC G0N 1E0',
      'Accès de Sainte-Praxède — Ch. du Lac-Aylmer, Sainte-Praxède',
    ],
    weatherRegion: 'Sherbrooke',
    coords: [45.88, -71.33],
    nearestCity: 'Disraeli',
  },

  // ─── L-B ─────────────────────────────────────────────────────────────────
  {
    id: 'lac-boivin',
    name: 'Lac Boivin',
    nameFr: 'Lac Boivin',
    nameEn: 'Lake Boivin',
    region: 'Estrie (Granby)',
    imageFile: 'lake-6.jpg',
    descFr: "Lac urbain accessible de Granby, le lac Boivin est intégré à un centre de conservation de la nature et est facilement praticable pour les pêcheurs de tous niveaux. Achigan, brochet et omble de fontaine y cohabitent dans un cadre agréable. La pêche y est souvent douce mais productive, surtout au printemps quand les eaux se réchauffent et que les poissons se rapprochent des berges accessibles.",
    descEn: "An accessible urban lake in Granby, Lac Boivin is part of a nature conservation centre and is easily fishable for anglers of all levels. Bass, pike, and brook trout coexist in a pleasant setting. Fishing is often relaxed but productive, especially in spring when waters warm and fish move closer to accessible banks.",
    species: ['Achigan', 'Grand Brochet', 'Truite Mouchetée'],
    bestSeason: 'Mai–Septembre',
    depth: 'Peu profond (3–10 m)',
    size: 'Petit lac (< 5 km²)',
    boatLaunches: [
      'Centre de la Nature du Lac Boivin — 700, rue Drummond, Granby, QC J2G 8B3 (accès pédestre, embarcations légères uniquement)',
    ],
    weatherRegion: 'Sherbrooke',
    coords: [45.52, -72.28],
    nearestCity: 'Granby',
  },
  {
    id: 'lac-brome',
    name: 'Lac Brome',
    nameFr: 'Lac Brome',
    nameEn: 'Brome Lake',
    region: 'Montérégie',
    imageFile: 'lake-7.jpg',
    descFr: "Lac populaire et facilement accessible de la Montérégie, le lac Brome est surtout connu pour son achigan à petite bouche, son brochet et son doré dans des eaux relativement peu profondes. Les quais, herbiers, pointes et fossés forment une mosaïque d'habitats diversifiés. L'été y est très fréquenté; les sorties tôt le matin ou en fin de soirée offrent les meilleures conditions, surtout pour l'achigan actif sur les structures.",
    descEn: "A popular and easily accessible Montérégie lake, Brome Lake is mainly known for smallmouth bass, pike, and walleye in relatively shallow water. Docks, weeds, points, and channels form a mosaic of diverse habitats. Summer sees heavy traffic; early morning or late evening outings offer the best conditions, especially for bass active on structure.",
    species: ['Achigan à Petite Bouche', 'Grand Brochet', 'Doré Jaune'],
    bestSeason: 'Juin–Septembre',
    depth: 'Peu à modérément profond (5–20 m)',
    size: 'Lac moyen (~15 km²)',
    boatLaunches: [
      'Rampe municipale de Knowlton — Rue Lakeside, Lac-Brome (Knowlton), QC J0E 1V0',
      'Accès de Foster — Route 139, Foster',
    ],
    weatherRegion: 'Sherbrooke',
    coords: [45.22, -72.50],
    nearestCity: 'Knowlton',
  },
  {
    id: 'lac-brompton',
    name: 'Lac Brompton',
    nameFr: 'Lac Brompton',
    nameEn: 'Lake Brompton',
    region: 'Estrie',
    imageFile: 'lake-8.jpg',
    descFr: "Lac de bonne qualité des Cantons-de-l'Est, Brompton se distingue par ses sections profondes qui soutiennent le touladi, combinées à des zones littorales productives pour l'achigan à petite bouche et le brochet. L'eau est relativement bonne et les cassures bien définies rendent la pêche au touladi accessible à ceux qui maîtrisent la pêche en profondeur. En été stable, les matins et soirées froides sont les moments phares.",
    descEn: "A quality Eastern Townships lake, Brompton stands out for its deep sections supporting lake trout, combined with productive littoral zones for smallmouth bass and pike. Water quality is relatively good and well-defined breaks make lake trout fishing accessible to those who master deep-water techniques. In stable summer conditions, cool mornings and evenings are the highlight windows.",
    species: ['Touladi', 'Achigan à Petite Bouche', 'Grand Brochet'],
    bestSeason: 'Mai–Octobre',
    depth: 'Profond (jusqu\'à 40 m)',
    size: 'Lac moyen (~10 km²)',
    boatLaunches: [
      'Rampe de Windsor — Route 143, Windsor, QC J1S 2L4',
      'Accès de Sherbrooke Nord — Ch. du Lac-Brompton, Sherbrooke',
    ],
    weatherRegion: 'Sherbrooke',
    coords: [45.42, -72.18],
    nearestCity: 'Sherbrooke',
  },

  // ─── L-C ─────────────────────────────────────────────────────────────────
  {
    id: 'lac-champlain-missisquoi',
    name: 'Lac Champlain (Baie Missisquoi)',
    nameFr: 'Lac Champlain — Baie Missisquoi',
    nameEn: 'Lake Champlain — Missisquoi Bay',
    region: 'Montérégie',
    imageFile: 'lake-9.jpg',
    descFr: "La baie Missisquoi est la portion québécoise du célèbre lac Champlain, un grand plan d'eau international à cheval sur le Vermont et le Québec. Peu profonde et bien réchauffée, la baie abrite une quantité impressionnante d'achigan, de brochet et de doré jaune, avec quelques perchaudes. Les herbiers denses, les battures et les quais constituent les zones clés en été. Un permis québécois est requis côté canadien; respectez les limites de prise de chaque côté de la frontière.",
    descEn: "Missisquoi Bay is the Quebec portion of the famous Lake Champlain, a large international water spanning Vermont and Quebec. Shallow and well-warmed, the bay holds an impressive quantity of bass, pike, and walleye, with some yellow perch. Dense weeds, flats, and docks are key areas in summer. A Quebec license is required on the Canadian side; respect catch limits on both sides of the border.",
    species: ['Achigan', 'Grand Brochet', 'Doré Jaune', 'Perchaude'],
    bestSeason: 'Mai–Octobre',
    depth: 'Peu profond (3–12 m)',
    size: 'Grande baie (~90 km²)',
    boatLaunches: [
      'Rampe de Venise-en-Québec — 1, rue de la Grève, Venise-en-Québec, QC J0J 2K0',
      'Rampe de Saint-Armand — Route 133, Saint-Armand',
      'Swanton Public Boat Launch — Swanton, VT (côté américain)',
    ],
    weatherRegion: 'Saint-Jean-sur-Richelieu',
    coords: [45.05, -73.08],
    nearestCity: 'Venise-en-Québec',
    permits: [
      {
        labelFr: '🎫 Permis de pêche sportive du Québec (requis — côté canadien)',
        labelEn: '🎫 Quebec Sport Fishing Permit (required — Canadian side)',
        url: 'https://mondossierchassepeche.gouv.qc.ca/'
      }
    ],
  },

  // ─── L-D ─────────────────────────────────────────────────────────────────
  {
    id: 'lac-deux-montagnes',
    name: 'Lac des Deux Montagnes',
    nameFr: 'Lac des Deux Montagnes',
    nameEn: 'Lake of Two Mountains',
    region: 'Laurentides / Montérégie',
    imageFile: 'lake-10.jpg',
    descFr: "Plan d'eau culte pour les amateurs de maskinongé près de Montréal, le lac des Deux Montagnes combine eau teintée, herbiers clairsemés, pointes et chenaux. On y pêche surtout le maskinongé, le brochet, le doré et l'achigan. Le début d'été peut être très bon, mais la réputation du lac se joue surtout en septembre et en octobre, quand les poissons trophées suivent les bordures externes et les structures battues par le vent.",
    descEn: "A legendary musky water close to Montreal, Lake of Two Mountains combines stained water, sparse weeds, points, and channels. Anglers mainly pursue musky, pike, walleye, and bass here. Early summer can be solid, but the lake's real reputation comes in September and October, when trophy fish follow outside edges and wind-blown structure.",
    species: ['Maskinongé', 'Grand Brochet', 'Achigan', 'Doré Jaune'],
    bestSeason: 'Juin–Octobre',
    depth: 'Modérée (5–20 m)',
    size: 'Grand lac (~130 km²)',
    boatLaunches: [
      'Rampes municipales de Deux-Montagnes (vignette résidentielle requise) — Deux-Montagnes, QC',
      'Parc Gagné — 270, boulevard des Prairies, Laval, QC H7N 2T9 (accès public)',
      'Rampe d\'Oka — Parc Oka, Route 344, Oka, QC J0N 1E0',
    ],
    weatherRegion: 'Laval',
    coords: [45.45, -74.0],
    nearestCity: 'Oka / Deux-Montagnes',
  },
  {
    id: 'lac-dorval',
    name: 'Lac Dorval',
    nameFr: 'Lac Dorval',
    nameEn: 'Lake Dorval',
    region: 'Abitibi-Témiscamingue',
    imageFile: 'lake-11.jpg',
    descFr: "Lac de pourvoirie en Abitibi, le lac Dorval est géré pour la pêche sportive de qualité avec un accent sur les trophées. Doré, brochet, esturgeon et maskinongé fréquentent ces eaux. La saison principale s'étend de mai à septembre, et l'accès est principalement via des lodges de pourvoirie qui limitent la pression. Une destination idéale pour ceux cherchant isolement et prise exceptionnelle.",
    descEn: "An outfitter lake in Abitibi, Lac Dorval is managed for quality sport fishing with a trophy focus. Walleye, pike, sturgeon, and musky all inhabit these waters. The main season runs May through September, and access is primarily through outfitter lodges that limit fishing pressure. An ideal destination for those seeking isolation and exceptional catch.",
    species: ['Doré Jaune', 'Grand Brochet', 'Esturgeon', 'Maskinongé'],
    bestSeason: 'Mai–Septembre',
    depth: 'Modérée à profonde (15–40 m)',
    size: 'Lac moyen (~30 km²)',
    boatLaunches: [
      'Accès via pourvoirie Dorval Lodge — renseignements : coordonnées GPS 47.44, -77.08',
      'Route forestière depuis Val-d\'Or — accès limité, permis requis',
    ],
    weatherRegion: 'Val-d\'Or',
    coords: [47.44, -77.08],
    nearestCity: 'Val-d\'Or',
  },

  // ─── L-E ─────────────────────────────────────────────────────────────────
  {
    id: 'lac-edouard',
    name: 'Lac Édouard',
    nameFr: 'Lac Édouard',
    nameEn: 'Lake Édouard',
    region: 'Mauricie',
    imageFile: 'lake-12.jpg',
    descFr: "Beau lac du Bouclier canadien en Haute-Mauricie, le lac Édouard est un classique pour l'omble de fontaine et le touladi. Ses eaux claires et froides, son fond rocheux et ses cassures profondes en font une destination de premier choix pour les amateurs de pêche salmonicole. Accessible depuis La Tuque via routes forestières, il offre une expérience sauvage et authentique loin des foules du sud.",
    descEn: "A beautiful Canadian Shield lake in Haute-Mauricie, Lac Édouard is a classic for brook trout and lake trout. Its clear, cold waters, rocky bottom, and deep breaks make it a premier destination for salmonid fishing. Accessible from La Tuque via forest roads, it offers a wild, authentic experience far from the southern crowds.",
    species: ['Truite Mouchetée', 'Touladi'],
    bestSeason: 'Mai–Juin, Septembre–Octobre',
    depth: 'Profond (30–55 m)',
    size: 'Lac moyen (~25 km²)',
    boatLaunches: [
      'Accès via La Tuque — Route 155 Nord puis chemin forestier vers lac Édouard',
      'Rampe informelle — coordonnées GPS : 47.65, -72.25',
    ],
    weatherRegion: 'La Tuque',
    coords: [47.65, -72.25],
    nearestCity: 'La Tuque',
  },
  {
    id: 'lac-evans',
    name: 'Lac Evans',
    nameFr: 'Lac Evans',
    nameEn: 'Lake Evans',
    region: 'Nord-du-Québec',
    imageFile: 'lake-13.jpg',
    descFr: "Grand lac de wilderness dans le Nord-du-Québec, le lac Evans est extrêmement reculé et peu pêché. Doré, brochet et touladi y atteignent des tailles remarquables grâce à la quasi-absence de pression de pêche. L'accès se fait principalement par hydravion depuis Chibougamau ou via la rivière Broadback. Une expédition sérieuse pour les pêcheurs qui cherchent l'aventure véritable au bout du monde québécois.",
    descEn: "A large wilderness lake in Nord-du-Québec, Lake Evans is extremely remote and minimally fished. Walleye, pike, and lake trout reach remarkable sizes thanks to near-zero fishing pressure. Access is primarily by floatplane from Chibougamau or via the Broadback River. A serious expedition for anglers seeking true adventure at the far end of Quebec.",
    species: ['Doré Jaune', 'Grand Brochet', 'Touladi'],
    bestSeason: 'Juin–Juillet',
    depth: 'Profond (30–70 m)',
    size: 'Grand lac (>200 km²)',
    boatLaunches: [
      'Accès par hydravion depuis Chibougamau (seule option pratique)',
      'Route via rivière Broadback — expédition avancée uniquement',
    ],
    weatherRegion: 'Chibougamau',
    coords: [50.91, -76.88],
    nearestCity: 'Chibougamau',
  },

  // ─── L-K ─────────────────────────────────────────────────────────────────
  {
    id: 'lac-kipawa',
    name: 'Lac Kipawa',
    nameFr: 'Lac Kipawa',
    nameEn: 'Lake Kipawa',
    region: 'Témiscamingue',
    imageFile: 'lake-14.jpg',
    descFr: "Lac de réputation internationale dans le Témiscamingue, Kipawa est renommé pour sa pêche au doré, au touladi et au brochet dans un décor de fjord spectaculaire. Son littoral très découpé crée une infinité de pointes, de baies, d'îles et de cassures. La pêche y est excellente du printemps à l'automne; les zones à courant près des resserrements et les cassures profondes des presqu'îles sont particulièrement productives.",
    descEn: "An internationally reputed lake in Témiscamingue, Kipawa is renowned for walleye, lake trout, and pike fishing in a spectacular fjord-like setting. Its highly indented shoreline creates an infinity of points, bays, islands, and breaks. Fishing is excellent from spring through fall; current zones near narrows and deep breaks off peninsulas are particularly productive.",
    species: ['Doré Jaune', 'Touladi', 'Grand Brochet'],
    bestSeason: 'Mai–Octobre',
    depth: 'Très profond (jusqu\'à 100 m)',
    size: 'Grand lac (~380 km²)',
    boatLaunches: [
      'Pourvoirie Kipawa — 11, chemin Kipawa, Témiscaming, QC J0Z 3R0',
      'Rampe de Kipawa Village — Chemin du Lac-Kipawa, Kipawa',
      'Accès de Témiscaming — Rue Kipawa, Témiscaming, QC J0Z 3R0',
    ],
    weatherRegion: 'Rouyn-Noranda',
    coords: [46.96, -78.96],
    nearestCity: 'Témiscaming',
  },

  // ─── L-L ─────────────────────────────────────────────────────────────────
  {
    id: 'lac-la-martre',
    name: 'Lac La Martre',
    nameFr: 'Lac La Martre',
    nameEn: 'Lake La Martre',
    region: 'Gaspésie',
    imageFile: 'lake-15.jpg',
    descFr: "Lac d'altitude en Gaspésie, La Martre se distingue par son eau froide, cristalline et ses ombles de fontaine de haute qualité. Situé dans un cadre montagneux spectaculaire près des Chic-Chocs, ce lac est accessible mais préservé. Le meilleur moment est le début de la saison (mai–juin) et la fin de l'automne, quand les truites sont les plus actives. Une destination pour les amateurs de pêche fine et de nature intacte.",
    descEn: "A high-altitude lake in Gaspésie, La Martre stands out for its cold, crystal-clear water and quality brook trout. Located in a spectacular mountain setting near the Chic-Choc Mountains, this lake is accessible but well preserved. Best time is early season (May–June) and late fall when trout are most active. A destination for refined fishing enthusiasts and lovers of pristine nature.",
    species: ['Truite Mouchetée'],
    bestSeason: 'Mai–Juin, Septembre–Octobre',
    depth: 'Modérée (15–35 m)',
    size: 'Petit lac (< 10 km²)',
    boatLaunches: [
      'Accès depuis Sainte-Anne-des-Monts — Route 299 vers les Chic-Chocs puis chemin forestier',
      'Mise à l\'eau rurale — coordonnées GPS : 49.20, -66.16',
    ],
    weatherRegion: 'Gaspé',
    coords: [49.20, -66.16],
    nearestCity: 'Sainte-Anne-des-Monts',
  },
  {
    id: 'lac-lareau',
    name: 'Lac Lareau',
    nameFr: 'Lac Lareau',
    nameEn: 'Lake Lareau',
    region: 'Haute-Mauricie',
    imageFile: 'lake-16.jpg',
    descFr: "Lac de pourvoirie reculé en Haute-Mauricie, Lareau est un paradis pour les pêcheurs à la mouche en quête d'omble de fontaine sauvage et d'omble arctique dans une nature vierge. La pêche y est intentionnellement limitée pour préserver l'exceptionnelle qualité des prises. Accessible principalement par hydravion, chaque sortie y est une expérience hors du commun dans le Bouclier canadien profond.",
    descEn: "A remote outfitter lake in Haute-Mauricie, Lareau is a fly-fishing paradise for anglers in pursuit of wild brook trout and Arctic char in pristine wilderness. Fishing is intentionally limited to preserve the exceptional quality of catches. Accessible mainly by floatplane, every outing here is an extraordinary experience deep in the Canadian Shield.",
    species: ['Truite Mouchetée', 'Omble Arctique'],
    bestSeason: 'Juin–Août',
    depth: 'Modérée à profonde (20–50 m)',
    size: 'Petit lac (< 20 km²)',
    boatLaunches: [
      'Accès par hydravion depuis La Tuque (recommandé)',
      'Route forestière depuis La Tuque — accès difficile, 4x4 requis',
    ],
    weatherRegion: 'La Tuque',
    coords: [48.13, -73.56],
    nearestCity: 'La Tuque',
  },

  // ─── L-M ─────────────────────────────────────────────────────────────────
  {
    id: 'lac-magog',
    name: 'Lac Magog',
    nameFr: 'Lac Magog',
    nameEn: 'Lake Magog',
    region: 'Estrie',
    imageFile: 'lake-17.jpg',
    descFr: "Lac urbain de Sherbrooke, le lac Magog offre une pêche accessible et diversifiée en plein cœur des Cantons-de-l'Est. Achigan à petite bouche, doré et grand brochet y sont les principales cibles dans un milieu relativement urbain mais encore productif. Les structures artificielles (quais, ponts, enrochements) jouent un rôle important. La pêche est bonne surtout tôt le matin ou le soir, à l'abri de la circulation nautique récréative.",
    descEn: "An urban lake in Sherbrooke, Lac Magog offers accessible and varied fishing in the heart of the Eastern Townships. Smallmouth bass, walleye, and northern pike are the main targets in a relatively urban but still productive setting. Artificial structures (docks, bridges, riprap) play an important role. Fishing is best early morning or evening, away from recreational boat traffic.",
    species: ['Achigan à Petite Bouche', 'Doré Jaune', 'Grand Brochet'],
    bestSeason: 'Mai–Septembre',
    depth: 'Modérée (10–20 m)',
    size: 'Lac moyen (~25 km²)',
    boatLaunches: [
      'Rampe du Parc Miner — 200, rue Miner, Sherbrooke (Magog), QC J1H 3L7',
      'Accès de Magog — Rue du Lac, Magog',
    ],
    weatherRegion: 'Sherbrooke',
    coords: [45.33, -72.03],
    nearestCity: 'Sherbrooke',
  },
  {
    id: 'lac-massawippi',
    name: 'Lac Massawippi',
    nameFr: 'Lac Massawippi',
    nameEn: 'Lake Massawippi',
    region: 'Estrie',
    imageFile: 'lake-18.jpg',
    descFr: "Lac élégant de l'Estrie, profond et relativement clair, Massawippi est surtout intéressant pour l'achigan, le brochet et la truite arc-en-ciel. Ses tombants, quais, pointes et rives rocheuses demandent de la précision et une présentation propre. L'été stable peut être très bon tôt et tard dans la journée, alors que le début de l'automne favorise souvent les poissons plus actifs sur les bordures.",
    descEn: "An elegant Eastern Townships lake, deep and relatively clear, Massawippi is mainly known for bass, pike, and rainbow trout. Its drop-offs, docks, points, and rocky shoreline demand precision and clean presentations. Stable summer weather can be very good early and late in the day, while early fall often brings more active fish to the edges.",
    species: ['Achigan', 'Grand Brochet', 'Truite Arc-en-ciel'],
    bestSeason: 'Juin–Septembre',
    depth: 'Très profond (jusqu\'à 86 m)',
    size: 'Lac moyen (~15 km²)',
    boatLaunches: [
      'Rampe de North Hatley — Rue Massawippi, North Hatley, QC J0B 2C0',
      "Rampe d'Ayer's Cliff — Rue du Lac, Ayer's Cliff, QC J0B 1C0",
    ],
    weatherRegion: 'Sherbrooke',
    coords: [45.22, -72.01],
    nearestCity: "Ayer's Cliff",
  },
  {
    id: 'lac-matapedia',
    name: 'Lac Matapédia',
    nameFr: 'Lac Matapédia',
    nameEn: 'Lake Matapedia',
    region: 'Gaspésie',
    imageFile: 'lake-19.jpg',
    descFr: "Grand lac naturel au cœur de la belle vallée de la Matapédia, ce plan d'eau est précieux pour la diversité de ses espèces: touladi, omble de fontaine et saumon atlantique y coexistent dans des eaux froides et bien oxygénées. Le lac est bordé de montagnes et offre une pêche sauvage remarquable. Juin à août est la meilleure période; les embouchures de rivières affluentes sont des points chauds reconnus.",
    descEn: "A large natural lake at the heart of the beautiful Matapédia Valley, this water is prized for its species diversity: lake trout, brook trout, and Atlantic salmon coexist in cold, well-oxygenated waters. The lake is flanked by mountains and offers remarkable wild fishing. June to August is the prime window; tributary river mouths are recognized hotspots.",
    species: ['Touladi', 'Truite Mouchetée', 'Saumon Atlantique'],
    bestSeason: 'Juin–Août',
    depth: 'Profond (30–60 m)',
    size: 'Grand lac (~70 km²)',
    boatLaunches: [
      'Rampe d\'Amqui — Boulevard Saint-Benoît, Amqui, QC G5J 2P8',
      'Accès de Causapscal — Route 132, Causapscal',
    ],
    weatherRegion: 'Gaspé',
    coords: [48.56, -67.55],
    nearestCity: 'Amqui',
  },
  {
    id: 'lac-megantic',
    name: 'Lac Mégantic',
    nameFr: 'Lac Mégantic',
    nameEn: 'Lake Mégantic',
    region: 'Estrie',
    imageFile: 'lake-20.jpg',
    descFr: "Lac profond et clair de l'Estrie, le lac Mégantic est réputé pour son touladi et sa truite arc-en-ciel dans une eau d'une clarté remarquable. Avec jusqu'à 119 m de profondeur, c'est un des lacs les plus profonds du Québec méridional. Pêcher en surface tôt en saison ou à grande profondeur en été donne les meilleurs résultats. Un plan d'eau magnifique entouré de collines boisées et au cachet authentique.",
    descEn: "A deep, clear lake in the Eastern Townships, Lac Mégantic is renowned for lake trout and rainbow trout in remarkably clear water. With depths up to 119 m, it is one of the deepest lakes in southern Quebec. Fishing near surface early in season or at great depth in summer yields best results. A beautiful water surrounded by forested hills with authentic character.",
    species: ['Touladi', 'Truite Arc-en-ciel', 'Achigan'],
    bestSeason: 'Mai–Octobre',
    depth: 'Très profond (jusqu\'à 119 m)',
    size: 'Lac moyen (~26 km²)',
    boatLaunches: [
      'Rampe municipale de Lac-Mégantic — 6081, rue Papineau, Lac-Mégantic, QC G6B 1H6',
      'Accès de Nantes — Route 161, Nantes',
    ],
    weatherRegion: 'Sherbrooke',
    coords: [45.54, -70.86],
    nearestCity: 'Lac-Mégantic',
  },
  {
    id: 'lac-memphremagog',
    name: 'Lac Memphrémagog',
    nameFr: 'Lac Memphrémagog',
    nameEn: 'Lake Memphremagog',
    region: 'Estrie',
    imageFile: 'lake-1.jpg',
    descFr: "Lac profond de l'Estrie aux eaux plus claires, Memphrémagog demande une approche plus fine que plusieurs grands plans d'eau du sud. On y trouve achigan, brochet, touladi, ouananiche et truite arc-en-ciel, avec des secteurs rocheux, des tombants marqués et des anses plus calmes. Le printemps tardif et le début d'automne sont souvent excellents, surtout pour l'achigan et le brochet actifs sur les transitions roche-herbier.",
    descEn: "A deep Eastern Townships lake with clearer water, Memphrémagog often requires a more refined approach than many large southern waters. It holds bass, pike, lake trout, landlocked salmon, and rainbow trout, with rocky structure, sharp drop-offs, and calmer coves. Late spring and early fall are often outstanding, especially for bass and pike working rock-to-weed transitions.",
    species: ['Touladi', 'Ouananiche', 'Achigan', 'Grand Brochet', 'Truite Arc-en-ciel'],
    bestSeason: 'Mai–Octobre',
    depth: 'Très profond (jusqu\'à 107 m)',
    size: 'Grand lac (~101 km²)',
    boatLaunches: [
      "Capitainerie de Magog — 353, rue de Hatley, Magog, QC J1X 3N2",
      'Rampe de Bolton-Est — Ch. Missisquoi, Bolton-Est',
      'Newport Public Boat Launch — Newport, VT (côté américain)',
    ],
    weatherRegion: 'Sherbrooke',
    coords: [45.0, -72.23],
    nearestCity: 'Magog',
  },
  {
    id: 'lac-mistassini',
    name: 'Lac Mistassini',
    nameFr: 'Lac Mistassini',
    nameEn: 'Lake Mistassini',
    region: 'Nord-du-Québec',
    imageFile: 'lake-2.jpg',
    descFr: "Plus grand lac naturel du Québec et véritable trésor halieutique, le lac Mistassini est légendaire pour ses ombles de fontaine trophées, ses touladis et ses dorés. Dans une nature absolument sauvage du Bouclier canadien, les poissons atteignent des tailles exceptionnelles. L'accès est principalement par hydravion ou route depuis Chibougamau. Juin et juillet sont optimaux; chaque sortie dans ce lac est une aventure mémorable.",
    descEn: "Quebec's largest natural lake and a true fishing treasure, Mistassini is legendary for trophy brook trout, lake trout, and walleye. In absolutely wild Canadian Shield country, fish reach exceptional sizes. Access is mainly by floatplane or road from Chibougamau. June and July are optimal; every outing on this lake is a memorable adventure.",
    species: ['Truite Mouchetée', 'Touladi', 'Doré Jaune'],
    bestSeason: 'Juin–Juillet',
    depth: 'Profond (30–80 m)',
    size: 'Très grand lac (~2 335 km²)',
    boatLaunches: [
      'Accès par hydravion depuis Chibougamau (recommandé)',
      'Route depuis Chibougamau — Route 167 Nord puis route Mistassini',
      'Marina de Mistissini — Rue Principale, Mistissini, QC G0W 1C0',
    ],
    weatherRegion: 'Chibougamau',
    coords: [50.93, -73.61],
    nearestCity: 'Mistissini',
  },

  // ─── L-N ─────────────────────────────────────────────────────────────────
  {
    id: 'lac-nantel',
    name: 'Lac Nantel',
    nameFr: 'Lac Nantel',
    nameEn: 'Lake Nantel',
    region: 'Laurentides',
    imageFile: 'lake-3.jpg',
    descFr: "Petit lac des Laurentides près de Mont-Tremblant, le lac Nantel est réputé pour son ensemencement régulier en omble de fontaine et en truite arc-en-ciel. Facilement accessible pour les familles et les pêcheurs débutants, il offre une expérience agréable dans un cadre naturel des Laurentides. La pêche est bonne de mai à juillet, avant que les eaux ne se réchauffent trop en plein été.",
    descEn: "A small Laurentians lake near Mont-Tremblant, Lac Nantel is known for regular stocking with brook trout and rainbow trout. Easily accessible for families and beginner anglers, it offers a pleasant experience in a natural Laurentians setting. Fishing is good from May to July, before the waters warm too much in midsummer.",
    species: ['Truite Mouchetée', 'Truite Arc-en-ciel'],
    bestSeason: 'Mai–Juillet',
    depth: 'Peu à modérément profond (5–20 m)',
    size: 'Petit lac (< 5 km²)',
    boatLaunches: [
      'Accès depuis Mont-Tremblant — Route 117 puis chemin local vers Nantel',
      'Rampe informelle — coordonnées GPS : 46.12, -74.33',
    ],
    weatherRegion: 'Mont-Tremblant',
    coords: [46.12, -74.33],
    nearestCity: 'Mont-Tremblant',
  },
  {
    id: 'lac-nominingue',
    name: 'Grand Lac Nominingue',
    nameFr: 'Grand Lac Nominingue',
    nameEn: 'Grand Lake Nominingue',
    region: 'Laurentides',
    imageFile: 'lake-4.jpg',
    descFr: "Grand plan d'eau des Laurentides dans le pays de la villégiature classique, le Grand lac Nominingue offre une pêche de qualité pour le touladi, le doré et l'achigan. Ses eaux claires, ses structures rocheuses et ses profondeurs variables en font un lac polyvalent selon les espèces. En été, les cassures à 7–15 m sont les zones phares pour le doré; le touladi exige une approche plus profonde surtout après juin.",
    descEn: "A large Laurentians lake in classic cottage country, Grand Lake Nominingue offers quality fishing for lake trout, walleye, and smallmouth bass. Its clear waters, rocky structure, and variable depths make it a versatile lake across species. In summer, breaks at 7–15 m are prime walleye zones; lake trout require a deeper approach, especially after June.",
    species: ['Touladi', 'Doré Jaune', 'Achigan à Petite Bouche'],
    bestSeason: 'Mai–Septembre',
    depth: 'Profond (jusqu\'à 45 m)',
    size: 'Grand lac (~35 km²)',
    boatLaunches: [
      'Rampe municipale de Nominingue — 2, rue du Lac, Nominingue, QC J0W 1R0',
      'Accès de L\'Ascension — Route 321, L\'Ascension',
    ],
    weatherRegion: 'Mont-Tremblant',
    coords: [46.39, -75.0],
    nearestCity: 'Nominingue',
  },

  // ─── L-O ─────────────────────────────────────────────────────────────────
  {
    id: 'lac-ouimet',
    name: 'Lac Ouimet',
    nameFr: 'Lac Ouimet',
    nameEn: 'Lake Ouimet',
    region: 'Laurentides',
    imageFile: 'lake-5.jpg',
    descFr: "Lac pittoresque des Laurentides à deux pas de Mont-Tremblant, le lac Ouimet est un plan d'eau de villégiature apprécié pour sa pêche au maskinongé, à l'achigan et au brochet. Les herbiers, les quais et les pointes rocheuses forment les structures clés. La saison estivale est la principale; les périodes de vent et de faible luminosité activent souvent les prédateurs en surface sur les herbiers bordiers.",
    descEn: "A scenic Laurentians lake steps from Mont-Tremblant, Lac Ouimet is a cottage lake appreciated for musky, bass, and pike fishing. Weeds, docks, and rocky points form key structures. Summer is the main season; wind and low-light periods often activate predators on surface across weed borders.",
    species: ['Maskinongé', 'Achigan à Petite Bouche', 'Grand Brochet'],
    bestSeason: 'Juin–Septembre',
    depth: 'Modérée (10–25 m)',
    size: 'Lac moyen (~10 km²)',
    boatLaunches: [
      'Accès de Mont-Tremblant Village — Chemin du Lac-Ouimet, Mont-Tremblant',
      'Rampe informelle — coordonnées GPS : 46.18, -74.58',
    ],
    weatherRegion: 'Mont-Tremblant',
    coords: [46.18, -74.58],
    nearestCity: 'Mont-Tremblant',
  },

  // ─── L-P ─────────────────────────────────────────────────────────────────
  {
    id: 'lac-pipmuacan',
    name: 'Lac Pipmuacan',
    nameFr: 'Lac Pipmuacan',
    nameEn: 'Lake Pipmuacan',
    region: 'Saguenay–Lac-Saint-Jean',
    imageFile: 'lake-6.jpg',
    descFr: "Vaste réservoir sauvage au nord du Saguenay, Pipmuacan est un territoire de pourvoirie et de wilderness réputé pour l'omble de fontaine, le touladi et le grand brochet. L'accès y est difficile, ce qui maintient une pression de pêche faible et des populations de poissons en excellente santé. Juillet et août sont les meilleurs mois; les tributaires, les baies abritées et les cassures entre zones peu profondes et profondes sont les plus productives.",
    descEn: "A vast wild reservoir north of the Saguenay, Pipmuacan is outfitter and wilderness territory renowned for brook trout, lake trout, and northern pike. Access is difficult, which maintains low fishing pressure and excellent fish populations. July and August are the best months; tributaries, sheltered bays, and breaks between shallow and deep zones are most productive.",
    species: ['Truite Mouchetée', 'Touladi', 'Grand Brochet'],
    bestSeason: 'Juin–Août',
    depth: 'Variable (15–60 m)',
    size: 'Très grand réservoir (~955 km²)',
    boatLaunches: [
      'Accès via pourvoiries du territoire — renseignements : AFRL Lac Pipmuacan',
      'Route forestière depuis Saguenay — accès limité, permis requis',
    ],
    weatherRegion: 'Saguenay',
    coords: [49.66, -69.83],
    nearestCity: 'Saguenay',
  },

  // ─── L-SA ────────────────────────────────────────────────────────────────
  {
    id: 'lac-saint-charles',
    name: 'Lac Saint-Charles',
    nameFr: 'Lac Saint-Charles',
    nameEn: 'Lake Saint-Charles',
    region: 'Capitale-Nationale',
    imageFile: 'lake-7.jpg',
    descFr: "Source d'eau potable pour Québec, le lac Saint-Charles est soumis à des restrictions strictes sur la navigation motorisée, ce qui en fait un plan d'eau au calme privilégié. Brochet, achigan et omble de fontaine y vivent dans des eaux encore saines malgré la proximité urbaine. La pêche à la chaloupe non motorisée ou depuis les berges accessibles est l'approche type. Un lac de proximité apprécié des Québécois qui veulent pêcher sans s'éloigner de la capitale.",
    descEn: "A drinking water source for Quebec City, Lac Saint-Charles is subject to strict motorboat restrictions, making it a privileged calm water body. Pike, bass, and brook trout live in waters still healthy despite urban proximity. Non-motorized boat fishing or from accessible banks is the standard approach. A close-to-home lake appreciated by Quebecers who want to fish without leaving the capital region.",
    species: ['Grand Brochet', 'Achigan', 'Truite Mouchetée'],
    bestSeason: 'Mai–Septembre',
    depth: 'Modérée (10–22 m)',
    size: 'Lac moyen (~8 km²)',
    boatLaunches: [
      'Accès riverain public — Rue du Lac-Saint-Charles, Québec (moteurs restreints)',
      'Parc linéaire du Lac-Saint-Charles — Chemin de la Rivière-Saint-Charles, Québec',
    ],
    weatherRegion: 'Québec',
    coords: [46.88, -71.32],
    nearestCity: 'Québec',
  },
  {
    id: 'lac-saint-francois',
    name: 'Lac Saint-François',
    nameFr: 'Lac Saint-François',
    nameEn: 'Lake Saint-François',
    region: 'Montérégie',
    imageFile: 'lake-8.jpg',
    descFr: "Grande eau frontalière du sud-ouest, le lac Saint-François est un élargissement du Saint-Laurent reconnu pour ses puissants prédateurs et ses secteurs balayés par le vent. Maskinongé, brochet, achigan et doré y occupent herbiers, pointes, chenaux et zones de transition. De juin à octobre, le lac peut être excellent; les journées avec un bon vent de travers activent souvent les poissons sur les bordures externes et les structures ouvertes.",
    descEn: "A major border water in the southwest, Lac Saint-François is a widening of the St. Lawrence known for strong predators and wind-driven structure. Musky, pike, bass, and walleye use its weeds, points, channels, and transition zones. From June through October it can be excellent, and days with good crosswind often activate fish along outside edges and open structure.",
    species: ['Maskinongé', 'Grand Brochet', 'Achigan', 'Doré Jaune'],
    bestSeason: 'Juin–Octobre',
    depth: 'Peu profond (3–12 m)',
    size: 'Grand lac (~170 km²)',
    boatLaunches: [
      'Rampe de Salaberry-de-Valleyfield — Boul. du Havre, Salaberry-de-Valleyfield, QC J6S 3M6',
      'Rampe de Dundee — Route 132, Dundee, QC J0S 1L0',
      'Accès d\'Akwesasne — Route 132, Saint-Régis, QC',
    ],
    weatherRegion: 'Salaberry-de-Valleyfield',
    coords: [45.15, -74.35],
    nearestCity: 'Salaberry-de-Valleyfield',
  },
  {
    id: 'lac-saint-jean',
    name: 'Lac Saint-Jean',
    nameFr: 'Lac Saint-Jean',
    nameEn: 'Lake Saint-Jean',
    region: 'Saguenay–Lac-Saint-Jean',
    imageFile: 'lake-9.jpg',
    descFr: "Grand lac ouvert, venteux et spectaculaire, le lac Saint-Jean est surtout associé à la ouananiche (saumon atlantique enclavé), mais il offre aussi du doré, du brochet et de l'omble de fontaine selon les secteurs. Les entrées de rivière, les pointes balayées par le vent et certaines battures font partie des zones clés. De juin à septembre, la fenêtre est la meilleure, avec des matinées et soirées particulièrement fortes.",
    descEn: "A huge open, windswept, dramatic lake, Lac Saint-Jean is best known for landlocked Atlantic salmon (ouananiche), but also offers walleye, pike, and brook trout depending on the area. River mouths, windblown points, and selected flats are key zones. June through September is the prime window, with dawn and evening often strongest when the lake has movement but remains fishable.",
    species: ['Ouananiche', 'Doré Jaune', 'Grand Brochet', 'Truite Mouchetée'],
    bestSeason: 'Juin–Septembre',
    depth: 'Peu profond (max 63 m, moy. 11 m)',
    size: 'Très grand lac (~1 053 km²)',
    boatLaunches: [
      'Marina de Roberval — 854, rue Arthur, Roberval, QC G8H 2M7',
      "Marina d'Alma — Rue du Pont, Alma, QC G8B 1B6",
      'Rampe de Dolbeau-Mistassini — Boul. des Pionniers, Dolbeau-Mistassini',
    ],
    weatherRegion: 'Saguenay',
    coords: [48.55, -72.0],
    nearestCity: 'Roberval / Alma',
  },
  {
    id: 'lac-saint-joseph',
    name: 'Lac Saint-Joseph',
    nameFr: 'Lac Saint-Joseph',
    nameEn: 'Lake Saint-Joseph',
    region: 'Capitale-Nationale',
    imageFile: 'lake-10.jpg',
    descFr: "Lac profond et clair de la région de Québec, le lac Saint-Joseph est apprécié pour son touladi et son achigan à petite bouche. Très développé en villégiature, il exige une bonne lecture des structures en profondeur pour le touladi. Les premières cassures à 10–20 m et les zones rocheuses peu profondes pour l'achigan sont les spots principaux. Un lac de cottage country accessible depuis la capitale avec une belle qualité de pêche.",
    descEn: "A deep, clear lake in the Quebec City region, Lac Saint-Joseph is appreciated for lake trout and smallmouth bass. Highly developed for cottaging, it requires good reading of deep structure for lake trout. First breaks at 10–20 m and shallow rocky zones for bass are the main spots. A cottage country lake accessible from the capital with quality fishing.",
    species: ['Touladi', 'Achigan à Petite Bouche'],
    bestSeason: 'Mai–Septembre',
    depth: 'Profond (jusqu\'à 50 m)',
    size: 'Lac moyen (~20 km²)',
    boatLaunches: [
      'Rampe de Fossambault-sur-le-Lac — Rue du Lac, Fossambault-sur-le-Lac, QC G3N 0E7',
      'Accès de Sainte-Catherine-de-la-Jacques-Cartier — Route 367, Sainte-Catherine',
    ],
    weatherRegion: 'Québec',
    coords: [46.88, -71.63],
    nearestCity: 'Fossambault-sur-le-Lac',
  },
  {
    id: 'lac-saint-louis',
    name: 'Lac Saint-Louis',
    nameFr: 'Lac Saint-Louis',
    nameEn: 'Lake Saint-Louis',
    region: 'Grand Montréal',
    imageFile: 'lake-11.jpg',
    descFr: "Élargissement du Saint-Laurent en aval de Montréal, le lac Saint-Louis est une eau très productive pour les pêcheurs sportifs de la grande région. Doré, achigan, maskinongé, brochet et même esturgeon fréquentent ces eaux riches. Les herbiers de l'île des Sœurs, les structures au large de Lachine et les bordures de courant du chenal principal sont des zones de choix. Un lac de proximité urbaine mais de grande qualité pour les prédateurs d'envergure.",
    descEn: "A widening of the St. Lawrence downstream of Montreal, Lac Saint-Louis is a highly productive water for sport anglers in the greater region. Walleye, bass, musky, pike, and even sturgeon inhabit these rich waters. The weed beds off Île des Soeurs, structures off Lachine, and current edges of the main channel are prime zones. An urban proximity lake of great quality for trophy predators.",
    species: ['Doré Jaune', 'Achigan', 'Maskinongé', 'Grand Brochet', 'Esturgeon'],
    bestSeason: 'Mai–Octobre',
    depth: 'Modérée (5–18 m)',
    size: 'Grand lac (~100 km²)',
    boatLaunches: [
      'Rampe de Lachine — 34e Avenue, Lachine (Montréal), QC H8T 1S3',
      'Rampe de LaSalle — Boulevard LaSalle, LaSalle (Montréal), QC H4G 3G2',
      'Accès de Dorval — Boulevard Beaconsfield, Baie-D\'Urfé, QC H9X 3E3',
    ],
    weatherRegion: 'Montréal',
    coords: [45.38, -73.81],
    nearestCity: 'Lachine / West Island',
  },
  {
    id: 'lac-saint-pierre',
    name: 'Lac Saint-Pierre',
    nameFr: 'Lac Saint-Pierre',
    nameEn: 'Lake Saint-Pierre',
    region: 'Mauricie / Centre-du-Québec',
    imageFile: 'lake-12.jpg',
    descFr: "Lac mythique de la plaine du Saint-Laurent et réserve de biosphère UNESCO, le lac Saint-Pierre est l'une des destinations les plus sérieuses au Québec pour le maskinongé, avec d'excellentes possibilités pour le doré, le brochet, l'achigan et l'esturgeon. Ses vastes herbiers, chenaux et corridors de marée concentrent les poissons selon les saisons. L'été est productif, mais les connaisseurs attendent surtout fin septembre-octobre.",
    descEn: "A mythical lake on the St. Lawrence plain and UNESCO biosphere reserve, Lac Saint-Pierre is one of Quebec's most serious musky destinations, with strong opportunities for walleye, pike, bass, and sturgeon. Its sprawling weed beds, channels, and tidal corridors concentrate fish by season. Summer is productive, but experienced anglers especially watch late September and October.",
    species: ['Maskinongé', 'Grand Brochet', 'Doré Jaune', 'Achigan', 'Esturgeon'],
    bestSeason: 'Juin–Octobre',
    depth: 'Peu profond (3–8 m)',
    size: 'Grand lac (~315 km²)',
    boatLaunches: [
      'Rampe de Saint-Ignace-de-Loyola — 2311, rang St-Pierre, Saint-Ignace-de-Loyola, QC J0K 2P0',
      'Rampe de Sorel-Tracy — Quai du Roi, Sorel-Tracy, QC J3P 1J3',
      'Accès de Pierreville — Rue du Fleuve, Pierreville',
    ],
    weatherRegion: 'Trois-Rivières',
    coords: [46.2, -72.85],
    nearestCity: 'Sorel-Tracy',
    permits: [
      {
        labelFr: '🎫 Permis de pêche sportive du Québec (requis)',
        labelEn: '🎫 Quebec Sport Fishing Permit (required)',
        url: 'https://mondossierchassepeche.gouv.qc.ca/'
      },
      {
        labelFr: '🏞️ Autorisation spéciale Lac Saint-Pierre (réserve UNESCO)',
        labelEn: '🏞️ Special Lac Saint-Pierre Authorization (UNESCO reserve)',
        url: 'https://afclacst-pierre.org/autorisation-permis-peche/'
      }
    ],
  },

  // ─── L-T ─────────────────────────────────────────────────────────────────
  {
    id: 'lac-temiscouata',
    name: 'Lac Témiscouata',
    nameFr: 'Lac Témiscouata',
    nameEn: 'Lake Témiscouata',
    region: 'Bas-Saint-Laurent',
    imageFile: 'lake-13.jpg',
    descFr: "Long lac glaciaire du Bas-Saint-Laurent, maintenant partiellement inclus dans le Parc national du Lac-Témiscouata, ce plan d'eau est remarquable pour son touladi et son omble de fontaine dans des eaux froides et bien oxygénées. La topographie allongée crée des zones de courant naturel et des dénivelés marqués propices aux salmonidés. Printemps et automne sont les meilleures saisons; les embouchures de ruisseaux tributaires sont des points chauds reconnus.",
    descEn: "A long glacial lake in Bas-Saint-Laurent, now partly included in Lac-Témiscouata National Park, this body of water is remarkable for lake trout and brook trout in cold, well-oxygenated waters. The elongated topography creates natural current zones and sharp depth changes conducive to salmonids. Spring and fall are the best seasons; tributary stream mouths are recognized hotspots.",
    species: ['Touladi', 'Truite Mouchetée'],
    bestSeason: 'Mai–Juin, Septembre–Octobre',
    depth: 'Profond (jusqu\'à 120 m)',
    size: 'Grand lac (~61 km²)',
    boatLaunches: [
      'Parc national du Lac-Témiscouata — 2655, route 232, Notre-Dame-du-Lac, QC G0L 1X0',
      'Rampe de Cabano — Rue du Lac, Témiscouata-sur-le-Lac (Cabano)',
    ],
    weatherRegion: 'Rimouski',
    coords: [47.66, -68.83],
    nearestCity: 'Témiscouata-sur-le-Lac',
    permits: [
      {
        labelFr: '🏞️ Droit d\'accès — Parc national du Lac-Témiscouata (Sépaq)',
        labelEn: '🏞️ Access fee — Lac-Témiscouata National Park (Sépaq)',
        url: 'https://www.sepaq.com/pq/tem/'
      }
    ],
  },
  {
    id: 'lac-tremblant',
    name: 'Lac Tremblant',
    nameFr: 'Lac Tremblant',
    nameEn: 'Lake Tremblant',
    region: 'Laurentides',
    imageFile: 'lake-14.jpg',
    descFr: "Lac magistral des Laurentides au pied du mont Tremblant, long de 12 km et très profond, le lac Tremblant est un plan d'eau de premier rang pour le touladi, la ouananiche et le maskinongé. Le décor est spectaculaire et la pêche de qualité y est maintenue par une bonne gestion. Les zones profondes du couloir central pour le touladi, les tombants rocheux pour l'achigan et les bordures d'herbiers pour le maskinongé définissent la stratégie.",
    descEn: "A majestic Laurentians lake at the foot of Mont-Tremblant, 12 km long and very deep, Lac Tremblant is a top-tier water for lake trout, landlocked salmon, and musky. The setting is spectacular and quality fishing is maintained through solid management. Deep zones of the central corridor for lake trout, rocky drop-offs for bass, and weed borders for musky define the strategy.",
    species: ['Touladi', 'Ouananiche', 'Maskinongé', 'Achigan'],
    bestSeason: 'Mai–Octobre',
    depth: 'Très profond (jusqu\'à 90 m)',
    size: 'Grand lac (~14 km de long)',
    boatLaunches: [
      'Parc national du Mont-Tremblant — 4860, Route 9, Saint-Côme, QC J0K 2B0 (accès Diable)',
      'Rampe de Saint-Jovite — Route 327, Mont-Tremblant, QC J8E 2Z7',
    ],
    weatherRegion: 'Mont-Tremblant',
    coords: [46.26, -74.60],
    nearestCity: 'Mont-Tremblant',
    permits: [
      {
        labelFr: '🏞️ Droit d\'accès — Parc national du Mont-Tremblant (Sépaq)',
        labelEn: '🏞️ Access fee — Mont-Tremblant National Park (Sépaq)',
        url: 'https://www.sepaq.com/pq/mot/'
      }
    ],
  },

  // ─── L-W ─────────────────────────────────────────────────────────────────
  {
    id: 'lac-waconichi',
    name: 'Lac Waconichi',
    nameFr: 'Lac Waconichi',
    nameEn: 'Lake Waconichi',
    region: 'Nord-du-Québec',
    imageFile: 'lake-15.jpg',
    descFr: "Lac de légende du Nord-du-Québec près de Chibougamau, Waconichi est célèbre pour ses ombles de fontaine trophées parmi les plus gros du Québec. Ses eaux profondes et froides du Bouclier canadien maintiennent des populations de poissons exceptionnelles, peu pressurées. L'accès est contrôlé et limité. Juin à août sont les meilleurs mois; les zones profondes et les embouchures de tributaires glaciaires sont les spots de rêve.",
    descEn: "A legendary lake in Nord-du-Québec near Chibougamau, Waconichi is famous for some of Quebec's largest trophy brook trout. Its deep, cold Canadian Shield waters maintain exceptional, little-pressured fish populations. Access is controlled and limited. June through August are the best months; deep zones and glacial tributary mouths are the dream spots.",
    species: ['Truite Mouchetée', 'Touladi'],
    bestSeason: 'Juin–Août',
    depth: 'Profond (40–80 m)',
    size: 'Lac moyen (~150 km²)',
    boatLaunches: [
      'Accès via pourvoirie — coordonnées GPS : 50.16, -73.91 (hydravion recommandé)',
      'Route forestière depuis Chibougamau — Route 167 Nord, accès limité',
    ],
    weatherRegion: 'Chibougamau',
    coords: [50.16, -73.91],
    nearestCity: 'Chibougamau',
  },

  // ─── RÉSERVOIRS ──────────────────────────────────────────────────────────
  {
    id: 'reservoir-baskatong',
    name: 'Réservoir Baskatong',
    nameFr: 'Réservoir Baskatong',
    nameEn: 'Baskatong Reservoir',
    region: 'Laurentides',
    imageFile: 'lake-16.jpg',
    descFr: "Immense réservoir des Laurentides de 320 km², le Baskatong est une destination prisée pour le doré jaune, le grand brochet, le touladi et le saumon de l'Atlantique enclavé. Son énorme superficie crée des conditions très diverses selon les secteurs: baies abritées, presqu'îles exposées, bois noyé et chenaux profonds. De mai à septembre, chaque secteur a ses heures de gloire; les couchers de soleil venteux et les matins de brume y produisent souvent les meilleures sorties.",
    descEn: "A massive 320 km² Laurentians reservoir, Baskatong is a prized destination for walleye, northern pike, lake trout, and landlocked Atlantic salmon. Its enormous surface creates very diverse conditions across sectors: sheltered bays, exposed peninsulas, flooded timber, and deep channels. May through September, each sector has its peak windows; windy sunsets and misty mornings often produce the best outings.",
    species: ['Doré Jaune', 'Grand Brochet', 'Touladi', 'Ouananiche'],
    bestSeason: 'Mai–Septembre',
    depth: 'Variable (10–55 m)',
    size: 'Très grand réservoir (320 km²)',
    boatLaunches: [
      'Accès de Mont-Laurier — Route 117 puis Route 309 Nord vers le réservoir',
      'Rampe forestière de Kiamika — Route 309, Kiamika, QC J0W 1G0',
      'Campings et pourvoiries riverains — consulter la ZEC Restigo',
    ],
    weatherRegion: 'Mont-Tremblant',
    coords: [46.80, -75.83],
    nearestCity: 'Mont-Laurier',
  },
  {
    id: 'reservoir-cabonga',
    name: 'Réservoir Cabonga',
    nameFr: 'Réservoir Cabonga',
    nameEn: 'Cabonga Reservoir',
    region: 'Outaouais / Abitibi-Témiscamingue',
    imageFile: 'lake-17.jpg',
    descFr: "Grand réservoir frontalier entre l'Outaouais et l'Abitibi, le Cabonga offre une pêche sauvage et peu fréquentée pour le doré, le brochet et le touladi. Son littoral très irrégulier, parsemé d'îles et de baies, crée d'innombrables habitats diversifiés. L'été y est la principale saison; les journées venteuses activent les prédateurs en surface sur les bordures d'herbiers, tandis que les matins calmes sont propices à la pêche en profondeur pour le touladi.",
    descEn: "A large reservoir on the border between Outaouais and Abitibi, Cabonga offers wild and lightly pressured fishing for walleye, pike, and lake trout. Its highly irregular shoreline, dotted with islands and bays, creates countless diverse habitats. Summer is the main season; windy days activate predators on weed edges while calm mornings suit deep-water lake trout fishing.",
    species: ['Doré Jaune', 'Grand Brochet', 'Touladi'],
    bestSeason: 'Juin–Août',
    depth: 'Modérée à profonde (15–45 m)',
    size: 'Grand réservoir (~550 km²)',
    boatLaunches: [
      'Accès via réserve faunique La Vérendrye — Route 117, La Vérendrye, QC',
      'Pourvoiries riveraines — consulter la Réserve Faunique La Vérendrye',
    ],
    weatherRegion: 'Val-d\'Or',
    coords: [47.30, -76.50],
    nearestCity: 'Val-d\'Or',
    permits: [
      {
        labelFr: '🏞️ Permis d\'accès — Réserve faunique La Vérendrye',
        labelEn: '🏞️ Access permit — La Vérendrye Wildlife Reserve',
        url: 'https://www.sepaq.com/rf/ver/'
      }
    ],
  },
  {
    id: 'reservoir-dozois',
    name: 'Réservoir Dozois',
    nameFr: 'Réservoir Dozois',
    nameEn: 'Dozois Reservoir',
    region: 'Abitibi-Témiscamingue',
    imageFile: 'lake-18.jpg',
    descFr: "Réservoir peu profond et hautement productif de l'Abitibi, Dozois est réputé pour sa pêche au doré et au grand brochet dans des eaux réchauffées et riches en nutriments. Les herbiers étendus, les battures et les zones d'inondation sont les habitats clés. Printemps et début d'été sont les périodes de pointe; les pêcheurs qui lisent bien les herbiers et les bordures de marécages récoltent des prises exceptionnelles.",
    descEn: "A shallow, highly productive Abitibi reservoir, Dozois is renowned for walleye and northern pike fishing in warm, nutrient-rich waters. Extensive weeds, flats, and flooded zones are key habitats. Spring and early summer are peak periods; anglers who read weeds and marsh edges well harvest exceptional catches.",
    species: ['Doré Jaune', 'Grand Brochet'],
    bestSeason: 'Mai–Juillet',
    depth: 'Peu profond (5–15 m)',
    size: 'Grand réservoir (~420 km²)',
    boatLaunches: [
      'Accès via Route 117 depuis Val-d\'Or — direction Louvicourt, puis route forestière',
      'Rampe forestière — coordonnées GPS : 47.60, -77.20 (confirmer accès)',
    ],
    weatherRegion: 'Val-d\'Or',
    coords: [47.60, -77.20],
    nearestCity: 'Val-d\'Or',
  },
  {
    id: 'reservoir-gouin',
    name: 'Réservoir Gouin',
    nameFr: 'Réservoir Gouin',
    nameEn: 'Gouin Reservoir',
    region: 'Haute-Mauricie',
    imageFile: 'lake-19.jpg',
    descFr: "Immense territoire de pourvoiries, d'îles, de baies et de bois noyé, le réservoir Gouin est une destination nordique de référence. Le doré jaune et le grand brochet y dominent, avec du touladi dans certains secteurs profonds et de l'omble de fontaine dans des eaux plus fraîches. De juin à septembre, la pêche est forte; en début d'été, les baies sombres et les structures de bois sont excellentes, tandis qu'en fin de saison les cassures et les pointes plus profondes prennent le relais.",
    descEn: "A vast northern maze of outfitter territory, islands, bays, and flooded timber, the Gouin Reservoir is a benchmark destination in Quebec. Walleye and northern pike are the main draws, with lake trout in certain deep sectors and brook trout in cooler connected waters. From June to September it fishes well; early summer shines in dark bays and timber, while late season shifts to deeper breaks and points.",
    species: ['Doré Jaune', 'Grand Brochet', 'Truite Mouchetée', 'Touladi'],
    bestSeason: 'Juin–Septembre',
    depth: 'Variable (10–40 m)',
    size: 'Très grand réservoir (~1 570 km²)',
    boatLaunches: [
      'Pourvoirie Barrage Gouin et Magnan — 431, Réservoir Gouin, La Tuque, QC',
      'Accès route forestière — coordonnées GPS : 48.35, -74.98',
      'Accès Parent — Route de Parent, Parent, QC G0X 2G0',
    ],
    weatherRegion: 'La Tuque',
    coords: [48.55, -74.8],
    nearestCity: 'Parent / La Tuque',
  },
  {
    id: 'reservoir-manicouagan',
    name: 'Réservoir Manicouagan',
    nameFr: 'Réservoir Manicouagan',
    nameEn: 'Manicouagan Reservoir',
    region: 'Côte-Nord',
    imageFile: 'lake-20.jpg',
    descFr: "L'« Œil du Québec » — ce cratère d'impact météoritique annulaire de 5 150 km² est l'un des plans d'eau les plus extraordinaires au monde. Le Réservoir Manicouagan abrite touladi, grand brochet et ouananiche dans des eaux froides et profondes. Son immensité, son isolement et son histoire géologique unique en font une destination d'exception. Accessible depuis Baie-Comeau par route 389, la saison va de juillet à août pour les conditions optimales.",
    descEn: "The 'Eye of Quebec' — this annular meteorite impact crater at 5,150 km² is one of the most extraordinary bodies of water on Earth. The Manicouagan Reservoir holds lake trout, northern pike, and landlocked salmon in cold, deep waters. Its immensity, isolation, and unique geological history make it an exceptional destination. Accessible from Baie-Comeau via Route 389, season runs July to August for optimal conditions.",
    species: ['Touladi', 'Grand Brochet', 'Ouananiche'],
    bestSeason: 'Juillet–Août',
    depth: 'Très profond (jusqu\'à 350 m)',
    size: 'Très grand réservoir (~1 942 km² anneau)',
    boatLaunches: [
      'Accès de Baie-Comeau — Route 389 Nord (environ 220 km) jusqu\'au barrage Manic-5',
      'Rampe Manic-5 — Route 389, km 220, Côte-Nord, QC',
    ],
    weatherRegion: 'Baie-Comeau',
    coords: [51.38, -68.70],
    nearestCity: 'Baie-Comeau',
  },

  // ─── RIVERS ──────────────────────────────────────────────────────────────
  {
    id: 'st-lawrence-river',
    name: 'Fleuve Saint-Laurent',
    nameFr: 'Fleuve Saint-Laurent',
    nameEn: 'St. Lawrence River',
    region: 'Montérégie / Montréal',
    imageFile: 'stlaurent.jpg',
    descFr: "Le Fleuve Saint-Laurent est l'artère vitale du Québec et l'un des systèmes fluviaux les plus riches du continent. Il abrite une diversité remarquable d'espèces: maskinongé, achigan à grande bouche, doré jaune, perchaude, esturgeon jaune, bar rayé et grand brochet cohabitent dans ses différents tronçons. Les mises à l'eau publiques sont nombreuses entre Montréal et Québec. Les pointes et les îles créent des couloirs de courant productifs pour les poissons actifs. La pêche à l'achigan et au doré est particulièrement forte entre juin et septembre.",
    descEn: "The St. Lawrence River is Quebec's vital artery and one of the richest river systems on the continent. It hosts remarkable species diversity: muskellunge, largemouth bass, walleye, yellow perch, lake sturgeon, striped bass, and northern pike coexist in its various sections. Public boat launches are plentiful between Montreal and Quebec City. Points and islands create productive current seams for active fish. Bass and walleye fishing is particularly strong from June through September.",
    species: ['Maskinongé', 'Achigan à Grande Bouche', 'Doré Jaune', 'Perchaude', 'Esturgeon', 'Grand Brochet'],
    bestSeason: 'Juin–Septembre',
    depth: 'Variable (3–100 m selon la section)',
    size: 'Fleuve majeur (~1 200 km de long)',
    boatLaunches: [
      'Rampe de Contrecœur — 550 rue Marie-Victorin, Contrecœur, QC J0L 1C0',
      'Rampe de Sorel-Tracy — Rue du Fleuve, Sorel-Tracy, QC J3P 1A1',
      'Rampe de Montmagny — 90 Rue du Bassin, Montmagny, QC G5V 3L4',
    ],
    weatherRegion: 'Montréal / Saint-Laurent Ouest',
    coords: [46.05, -73.10],
    nearestCity: 'Sorel-Tracy',
    permits: [{
      labelFr: 'Permis de pêche sportive du Québec requis. Pour l\'esturgeon: réglementation spécifique MRNF.',
      labelEn: 'Quebec sport fishing permit required. For sturgeon: specific MRNF regulations apply.',
      url: 'https://peche.faune.gouv.qc.ca/fr/peche-sportive',
    }],
  },
  {
    id: 'riviere-outaouais',
    name: 'Rivière des Outaouais',
    nameFr: 'Rivière des Outaouais',
    nameEn: 'Ottawa River (Rivière des Outaouais)',
    region: 'Outaouais',
    imageFile: 'outaouais.jpg',
    descFr: "La Rivière des Outaouais forme la frontière naturelle entre le Québec et l'Ontario et constitue un corridor de pêche exceptionnel. L'achigan à petite bouche, le maskinongé, le doré jaune, la perchaude et le grand brochet sont les principales cibles. Les rapides, les îles et les plats rocheux entre Gatineau et Hawkesbury offrent des milliers de postes. La pêche au maskinongé y est reconnue parmi les meilleures au Canada. La rivière est navigable sur la majeure partie de son cours accessible.",
    descEn: "The Ottawa River forms the natural boundary between Quebec and Ontario and is an exceptional fishing corridor. Smallmouth bass, muskellunge, walleye, yellow perch, and northern pike are the main targets. Rapids, islands, and rocky flats between Gatineau and Hawkesbury offer thousands of holding spots. Muskellunge fishing is recognized among the best in Canada. The river is navigable over most of its accessible stretch.",
    species: ['Achigan à Petite Bouche', 'Maskinongé', 'Doré Jaune', 'Perchaude', 'Grand Brochet'],
    bestSeason: 'Mai–Octobre',
    depth: 'Variable (2–30 m)',
    size: 'Grande rivière (~1 271 km)',
    boatLaunches: [
      'Rampe de Gatineau — 280 Boul. Fournier, Gatineau, QC J8Z 1T2',
      'Rampe de Grenville — Rue de la Rivière, Grenville, QC J0V 1J0',
      'Accès de Portage-du-Fort — Route 148, Portage-du-Fort, QC J0X 2T0',
    ],
    weatherRegion: 'Gatineau / Rivière des Outaouais',
    coords: [45.48, -75.70],
    nearestCity: 'Gatineau',
    permits: [{
      labelFr: 'Permis de pêche sportive du Québec requis. Vérifier la réglementation de zone.',
      labelEn: 'Quebec sport fishing permit required. Check zone-specific regulations.',
      url: 'https://peche.faune.gouv.qc.ca/fr/peche-sportive',
    }],
  },
  {
    id: 'riviere-richelieu',
    name: 'Rivière Richelieu',
    nameFr: 'Rivière Richelieu',
    nameEn: 'Richelieu River',
    region: 'Montérégie',
    imageFile: 'richelieu.jpg',
    descFr: "Reliant le Lac Champlain au Fleuve Saint-Laurent, la Rivière Richelieu est l'une des meilleures rivières à achigan à grande bouche du Québec. Ses eaux chaudes et riches en herbiers accueillent aussi le maskinongé, le doré, le grand brochet et la perchaude. Les quais, les pontons, les herbiers et les structures rocheuses sont les postes à prospecter. Saint-Jean-sur-Richelieu est le centre névralgique de la pêche sportive sur cette rivière.",
    descEn: "Connecting Lake Champlain to the St. Lawrence River, the Richelieu River is one of Quebec's best largemouth bass rivers. Its warm, weed-rich waters also host muskellunge, walleye, northern pike, and yellow perch. Docks, marinas, weed beds, and rocky structures are the spots to prospect. Saint-Jean-sur-Richelieu is the hub of sport fishing on this river.",
    species: ['Achigan à Grande Bouche', 'Maskinongé', 'Doré Jaune', 'Grand Brochet', 'Perchaude'],
    bestSeason: 'Mai–Septembre',
    depth: 'Peu à modérément profond (2–15 m)',
    size: 'Rivière moyenne (~130 km)',
    boatLaunches: [
      'Rampe de Saint-Jean-sur-Richelieu — 100 Rue du Quai, Saint-Jean-sur-Richelieu, QC J2X 2K1',
      'Rampe de Chambly — 100 Rue Bourgogne, Chambly, QC J3L 1X4',
    ],
    weatherRegion: 'Saint-Jean-sur-Richelieu',
    coords: [45.32, -73.27],
    nearestCity: 'Saint-Jean-sur-Richelieu',
    permits: [{
      labelFr: 'Permis de pêche sportive du Québec requis.',
      labelEn: 'Quebec sport fishing permit required.',
      url: 'https://peche.faune.gouv.qc.ca/fr/peche-sportive',
    }],
  },
  {
    id: 'riviere-saint-maurice',
    name: 'Rivière Saint-Maurice',
    nameFr: 'Rivière Saint-Maurice',
    nameEn: 'Saint-Maurice River',
    region: 'Mauricie',
    imageFile: 'lake-2.jpg',
    descFr: "La Rivière Saint-Maurice est une rivière à courant vif de la Mauricie, traversant des paysages sauvages entre La Tuque et Trois-Rivières. Elle est réputée pour ses populations de doré jaune, de truite mouchetée et de grand brochet. Les zones calmes en aval des rapides, les embouchures de tributaires et les postes rocheux sont les plus productifs. La section entre La Tuque et Shawinigan offre d'excellentes opportunités dans un décor naturel spectaculaire.",
    descEn: "The Saint-Maurice River is a swift-water river in Mauricie, flowing through wild landscapes between La Tuque and Trois-Rivières. It is renowned for its populations of walleye, brook trout, and northern pike. Calm eddies below rapids, tributary mouths, and rocky holds are most productive. The section between La Tuque and Shawinigan offers excellent opportunities in spectacular natural scenery.",
    species: ['Doré Jaune', 'Truite Mouchetée', 'Grand Brochet'],
    bestSeason: 'Juin–Septembre',
    depth: 'Variable (1–20 m)',
    size: 'Grande rivière (~563 km)',
    boatLaunches: [
      'Accès de La Tuque — 245 Rue Commerciale, La Tuque, QC G9X 1G4',
      'Accès de Shawinigan — 2200 Boul. des Hêtres, Shawinigan, QC G9N 8H7',
    ],
    weatherRegion: 'Shawinigan / Saint-Maurice',
    coords: [47.50, -73.50],
    nearestCity: 'La Tuque',
    permits: [{
      labelFr: 'Permis de pêche sportive du Québec requis. Vérifier ZEC et réserves fauniques.',
      labelEn: 'Quebec sport fishing permit required. Check ZEC and wildlife reserves.',
      url: 'https://peche.faune.gouv.qc.ca/fr/peche-sportive',
    }],
  },
  {
    id: 'riviere-saguenay',
    name: 'Rivière Saguenay',
    nameFr: 'Rivière Saguenay',
    nameEn: 'Saguenay River',
    region: 'Saguenay–Lac-Saint-Jean',
    imageFile: 'lake-3.jpg',
    descFr: "Impressionnant fjord fluvial de 155 km, la Rivière Saguenay s'étend de Chicoutimi jusqu'au Fleuve Saint-Laurent à Tadoussac. Ses eaux profondes et froides abritent esturgeon, omble chevalier, touladi et saumon atlantique. La section en amont de Chicoutimi est plus accessible pour la pêche sportive, notamment pour le doré et le grand brochet. La rive nord entre Saguenay et Tadoussac offre des sites de pêche exceptionnels.",
    descEn: "An impressive river fjord of 155 km, the Saguenay River extends from Chicoutimi to the St. Lawrence River at Tadoussac. Its deep, cold waters host lake sturgeon, arctic char, lake trout, and Atlantic salmon. The section upstream of Chicoutimi is more accessible for sport fishing, notably for walleye and northern pike. The north shore between Saguenay and Tadoussac offers exceptional fishing sites.",
    species: ['Esturgeon', 'Touladi', 'Doré Jaune', 'Grand Brochet', 'Saumon Atlantique'],
    bestSeason: 'Juin–Septembre',
    depth: 'Très profond (jusqu\'à 275 m dans le fjord)',
    size: 'Rivière/Fjord majeur (~155 km)',
    boatLaunches: [
      'Rampe de Chicoutimi — 100 Rue Salaberry, Saguenay (Chicoutimi), QC G7J 1G3',
      'Accès de Saint-Fulgence — 230 Rue de la Rivière, Saint-Fulgence, QC G0V 1S0',
    ],
    weatherRegion: 'Saguenay',
    coords: [48.26, -70.88],
    nearestCity: 'Saguenay (Chicoutimi)',
    permits: [{
      labelFr: 'Permis de pêche sportive du Québec requis. Esturgeon: réglementation stricte MRNF.',
      labelEn: 'Quebec sport fishing permit required. Sturgeon: strict MRNF regulations.',
      url: 'https://peche.faune.gouv.qc.ca/fr/peche-sportive',
    }],
  },
]

// Sort alphabetically by nameFr
waters.sort((a, b) => a.nameFr.localeCompare(b.nameFr, 'fr', { sensitivity: 'base' }))
